### ISSUE TITLE
tooltip should not takes up space when it's hidden

### ISSUE THREAD

**Issue by KynoYang** [720kb/angular-tooltips#10]
@45kb hi, I got a problem caused by visibility: hidden since "hidden" here means "can't be seen but take up space". 

In my project, the whole page's height is 100vh. However, I found after using tooltips, the body element could be scrolled. I tried several times and found it's tooltips that are below the body element before they are initialized. 

So far, I have to set tooltip's top to avoid it taking space below body element.

So, I think maybe we should use display: none or block to control tooltip's visibility.

**Comment by 45kb** [comment]
@KynoYang  Hi, yes we can try using display:none; display:visible | initial; , just a replacement of visibility as it is now, then we should also make tooltip out of the screen when hidden ...

**Comment by KynoYang** [comment]
Awesome!  
display:none is enough I think. I'll do it later.

**Comment by 45kb** [comment]
Ok :) thank you

**Comment by KynoYang** [comment]
It seems that opacity animation can't work with "display:none".
Too bad. (>﹏<)
I‘ll think about other ways.

**Comment by 45kb** [comment]
:)
Imho, referring to this https://github.com/720kb/angular-tooltips/issues/9

We should do something like this:

tooltip {
display:none;
opacity:0;
}
tooltip.open {
display:visible;
display:initial;
}

tooltip.open.fast{
transition: opacity 0.1 linear;
opacity:1;
}

tooltip.open.medium{
transition: opacity 0.3 linear;
opacity:1;
}

tooltip.open.slow{
transition: opacity 0.5 linear;
opacity:1;
}

The only problem that comes in my mind is when you want to specify your own animation duration in milliseconds : 

< a tooltip tooltip-speed="900" > tooltip </ a >

**Comment by KynoYang** [comment]
@45kb You can change the style of an element directly in js. Or, using ng-style can do the same thing. So, it's not a problem. :)

**Comment by 45kb** [comment]
@KynoYang  don't use ng-style or css in js please :) the method i shown above is ok, it's pure css at the end and it is the correct way trust me ;)

**Comment by KynoYang** [comment]
@45kb  OK， I see.

**Comment by 45kb** [comment]
@KynoYang  Hi :) did you gave up then?

**Comment by KynoYang** [comment]
@45kb Sorry. It was Spring Festival Vacation recently. I have to do my job first before the vacation. Tomorrow I'll go back to work and have time to update this pr soon. :） 

Sorry for waiting that much time.

**Comment by 45kb** [comment]
@KynoYang  Hi Kyno, absolutely no problems, that's great!

 Many thanks for you time.

**Comment by 45kb** [comment]
@KynoYang  sorry it's me again, was this issue fixed or not, sorry but i don't remember about this specific issue, wasn't it fixed by you in the lastest PRs?

**Comment by 45kb** [comment]
looks closed
