### ISSUE TITLE
tooltip-view scope

### ISSUE THREAD

**Issue by erapoport** [720kb/angular-tooltips#101]
I tried using `tooltip-view` and `tooltip-view-ctrl` and I am able to see the scope variables from the scope where the tooltip was created, but I have to do `$parent.$parent` to get to them.

Is there a recommended way to pass scope arguments to `tooltip-view`?

Thanks

**Comment by panzerdp** [comment]
Hi @erapoport,
I few days ago I faced the same problem :).
Please check the Readme file, where it is mentioned how to use the model passed to the tooltip.

You can set a model for your tooltip view using the `tooltip-view-model=""`

```html
<a href="#" tooltips tooltip-title="tip" tooltip-view-model="myModel" tooltip-view="path/to/view.html">Tooltip me</a>
```
then use it in your tooltip html template:

```html
<!-- path/to/view.html -->
<span>Tooltip me with data - {{ tooltipViewModel }}</span>
```

Notice that this attribute is available in master branch only (a new version with this is not released yet).
Enjoy!

**Comment by 45kb** [comment]
Hi, a new version of the module is available, this version should fix this, thank you.

**Comment by Sampath-Lokuge** [comment]
@panzerdp Can you tell me where is the place for the explanation about `tooltip-view-model` on the Readme doc ? I couldn't find out it.Thanks.

**Comment by panzerdp** [comment]
@Sampath-Lokuge I think starting version 1.0.0 (which was a directive full rewrite) this attribute is not available anymore.

**Comment by Sampath-Lokuge** [comment]
@panzerdp Oh..Then do you know how can we do this kind of complex requirement with this or any other Tooltip directive ? Thanks.

**Comment by Sampath-Lokuge** [comment]
@panzerdp My exact requirement is here.Please see that too.

[Complex logic as ToolTip on the Angular UI Grid's cellTemplate](http://stackoverflow.com/questions/38243595/complex-logic-as-tooltip-on-the-angular-ui-grids-celltemplate)

**Comment by tlkiong** [comment]
Can we at least reopen this issue?
