### ISSUE TITLE
Tooltips don't work inside DOM elements that have their visibility dynamically udpated

### ISSUE THREAD

**Issue by rrafael27** [720kb/angular-tooltips#103]
```
<body>
<div id="appView"> ... </div>
<div id="other"> ... </div>
<div id="loading"> Loading </div>
</body>
```

#appView, #other and #loading have their visibility dynamically updated. Currently, when adding tooltips inside #appView, #other and #loading divs, the tooltips are appended to `<body>`. That way they cease to work properly (they don't get displayed).

I have managed to fix this issue by changing two lines in angular-tooltips.js. I added a directive attribute "tooltip-parent" where one can register the id for the tooltip parent container.

**Comment by wouldgo** [comment]
closed by PR.
