### ISSUE TITLE
Positioning problem

### ISSUE THREAD

**Issue by webmatrixxxl** [720kb/angular-tooltips#107]
Hi. When tooltip is at very right side of the page content is shown down side causing page horizontal scroll. The right behaviour is showing content on the left side.

https://infinit.io/_/89TqiZM

**Comment by 45kb** [comment]
Hi @webmatrixxxl  you can specify ```tooltip-try="false"``` togheter with ```tooltip-side="left"``` for your case.

However, we are working on a new version of this module that will be more efficient!

**Comment by LulzAugusto** [comment]
@45kb Hi. I was having the same problem and `tooltip-try="false"` worked like a charm. But why was it needed? The docs says it should be false by default

**Comment by 45kb** [comment]
@LulzAugusto typo in the readme, by default it is true. Anyway, we are going to release soon a new version of the module, keep an eye later or in few days

**Comment by LulzAugusto** [comment]
@45kb I will. Thanks!
