### ISSUE TITLE
Tooltip doesn't close under IOS

### ISSUE THREAD

**Issue by alexanderluedeke** [720kb/angular-tooltips#108]
Example: Open the project demo page in Safari on a iPad with IOS 8
http://720kb.github.io/angular-tooltips/
You will see, that a tooltip only will disappear, when you mouse over another button. This is not satisfying for me.

I think, mouseleave is not implemented by the Safari browser, so I tried to override the tooltip-hide-trigger attribute with "mouseout" for example, but nothing worked. 

The only working approach is using the "click" event as trigger for showing and hiding the tooltip. But I would like use mouse over instead of click. Any ideas? 

Thanks in advance! alexander

**Comment by gae123** [comment]
@alexanderluedeke iOS is a touch platform but you write "mouse over" that do not make sense for a touch interface. Could you please clarify the exact steps, what you expect and what you get. I agree there is an issue there as well but I want to make sure we are referring to the same issue.

**Comment by alexanderluedeke** [comment]
@gae123 You are right. I mean the counterpart on such devices. I think, a touch event should close the tooltip, when it's shown.

**Comment by 45kb** [comment]
@alexanderluedeke Hi, sorry for the delay we are working on the new version of this module, anyway, have you tried using ```tooltip-show-trigger="touchstart"``` and ```tooltip-hide-trigger="touchend"``` ?

**Comment by alexanderluedeke** [comment]
Hi! If I remember correctly, no, because it was not mentioned in the documentation. ;-)

**Comment by 45kb** [comment]
@alexanderluedeke Hi, you have them explained here: https://github.com/720kb/angular-tooltips#tooltip-triggers

However, if you try, please let know if this fix the problem, i am guessing for sure...

**Comment by alexanderluedeke** [comment]
Yes, but without mentioning touchstart or touchend. ;-) 
To be honest, I'm using bootstrap popovers, instead.

**Comment by 45kb** [comment]
@alexanderluedeke  we can't mention every event that is in the API, we serve the wrapper put inside what you want :+1: 

However no problems, just take a look at the repo later if you want to use this module, we are moving on a total new version of this module in some day that will be much more better and fixed than the actual.

Thank you.
