### ISSUE TITLE
Doesn't work well with tables

### ISSUE THREAD

**Issue by laxu** [720kb/angular-tooltips#112]
I have had issues with this component when applying tooltips on items inside tables. For example if I have a link inside a table header or table body row td then tooltip will often position itself wrong: either on bottom when it should be on top or partially outside the screen. 
On table body rows the tooltip will position itself wrong (with tip at the top of the cell instead of the item inside it) and often becomes hard to show (tooltip will render on top of table cell which has the opener element).

**Comment by alisazhang** [comment]
I am facing the same problem with you, have you find the way to solve this problem?

**Comment by laxu** [comment]
I decided to use angular-foundation's tooltips for those situations since I was using it in the first place. Just had to style them to match what I had for 720kb tooltips.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.

**Comment by alisazhang** [comment]
Thanks for your attention, I have solved the problem using 'tooltip-try=false'.

**Comment by 45kb** [comment]
Hi @alisazhang glad if it works, i suggest you anyway to give a try at the new version of the module is faster and easier, practically all is done via css and not via js, and tooltip-try="" (which now is called tooltip-smart="") is false by default
