### ISSUE TITLE
Model Tag as View

### ISSUE THREAD

**Issue by mstampfli** [720kb/angular-tooltips#113]
Hi There,

Small question, is it possible to do the "tooltip-view="tooltiptmpl.html"" like this: "tooltip-view="{{test}}.html""?

This would actually be really cool!

Cheers
Mike

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.
