### ISSUE TITLE
when scroll=true, scrolling elements beyond the bottom of the page can cause additional scrollbars to appear due to hidden tooltips rendering outside the viewport

### ISSUE THREAD

**Issue by whboyd** [720kb/angular-tooltips#114]
Tooltips attached to scrollable elements with scroll=true Can cause an unwanted page-level scrollbar to render.

For example, if a tooltip is initialized for an item near the bottom of a scrollable list and the user scrolls back to the top of that list, the tooltip may end up being positioned past the bottom of the page. This may cause an unwanted page-level scrollbar to appear. Even if the tooltip is appropriately hidden when not visible using display: none;, the scrollbar may appear briefly if the user scrolls quickly, causing the tooltip to move past the bottom of the page before it has a chance to hide itself.

**Comment by antonellopasella** [comment]
Same problem.
It will fix to display:none instead of opacity/0 and visibility/hidden?

**Comment by whboyd** [comment]
Yes, display:none; fixes at least part of the problem.

However, you may still get an additional scroll bar appearing for a few milliseconds if you scroll quickly and the tooltip goes outside the page before becoming hidden.

**Comment by antonellopasella** [comment]
This is my forked version
https://github.com/antonellopasella/angular-tooltips/commit/a10d332bf7d06d6552be873fc18ab35cbc483086

**Comment by wouldgo** [comment]
Hi,

we'are writing from scratch all the directive, refactoring the current behavior and the scenario you provide should not be present anymore.

The actual status of our refactor is in the `next` branch. All is almost done we've only a issue on positioning the tooltip when the 'tooltipped' content have some padding or margin.
If you have any ideas about this issue you're welcome.

Have a great day,
Dario

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.
