### ISSUE TITLE
tooltip-parent does not work when angular-tooltips is installed from npm

### ISSUE THREAD

**Issue by hannupekka** [720kb/angular-tooltips#115]
Seems to be missing this fix.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.
