### ISSUE TITLE
Show tooltip next to checkbox

### ISSUE THREAD

**Issue by dmnrmr** [720kb/angular-tooltips#116]
How can i make tooltip show near checkbox instead of text? I though I need to use "parent" option, but it does nothing.

Also tooltip is aligned middle relative to text. Is there a way to align it at top?

![screenshot from 2015-11-12 16-47-11](https://cloud.githubusercontent.com/assets/7805266/11121237/4e6f22de-895d-11e5-9f44-c9ceed514368.png)

![screenshot from 2015-11-12 16-48-08](https://cloud.githubusercontent.com/assets/7805266/11121239/4ea0055c-895d-11e5-85f5-b36817c58001.png)

**Comment by 45kb** [comment]
Hi, so you already tryed `<input type="checkbox" tooltips/>` and it doesn't work?

**Comment by dmnrmr** [comment]
I've added "tooltips" to text near checkbox because I want tooltip to be shown when you hover text, not checkbox.

**Comment by 45kb** [comment]
Ok understood now, you could use your own custom class like and do like this:

```css
._720kb-tooltip.checkbox{
        margin-left:-30px;
  }
```
```html
<input type="checkbox"/> <span tooltips tooltip-side="left" tooltip-class="checkbox">My text </span>
```

I am afraid this is the only way.

**Comment by dmnrmr** [comment]
Thanks, will try it. But what should "parent" option do? And also is there a way to align tooltip?

**Comment by 45kb** [comment]
What you mean by "align" ? 

Probably parent option could work tho, it should give you the possibility to setup a different parent for the directive like this:

```html
<div id="parent">
<input type="checkbox"/> 
<span tooltips tooltip-side="left" tooltip-parent="parent">My text</span>
</div>
```

Try this too :)

**Comment by dmnrmr** [comment]
Check 2 pics in first post. Notice the triangle position.

**Comment by 45kb** [comment]
I still not understading what you mean, do you mean move the triangle? 

The screen shows two different positions but they are aligned as i can see...

**Comment by dmnrmr** [comment]
The text that has "tooltips" attribute assigned in the middle of tooltip. I want it to be at the top.

![1](https://cloud.githubusercontent.com/assets/7805266/11124963/1f6af2c0-8970-11e5-8de3-74c96215d2d0.png)
![2](https://cloud.githubusercontent.com/assets/7805266/11124962/1f683468-8970-11e5-89fe-0a837b59c9e4.png)

**Comment by 45kb** [comment]
Ok understood now, you could add some css using tooltip-class="custom-class" some margin-top for example :)

**Comment by dmnrmr** [comment]
But tooltip height is dynamic, based on content. So css won't work.

**Comment by 45kb** [comment]
Can you join here https://gitter.im/720kb/angular-tooltips is more comfortable and faster
