### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by simison** [720kb/angular-tooltips#122]
Would be cool for a quick preview what has changed.

Thanks!

**Comment by WeKyle** [comment]
+1. Migrating from 0.x wasn't very intuitive

**Comment by renestalder** [comment]
+1

**Comment by wouldgo** [comment]
I've redacted a changelog from 1.0.5 to 1.0.7 by now; at the moment of the 1.x.x release we thought (probably naïvely) that the Readme.md could be enough.

For futures releases we continue to write down on CHANGELOG.

**Comment by renestalder** [comment]
Well, I kept it at v0.1.25 because of missing upgrade guide or breaking changes description, also limited time to find out myself.
