### ISSUE TITLE
html in tooltip-template

### ISSUE THREAD

**Issue by cecilphillip** [720kb/angular-tooltips#123]
in the ReadMe, it says tooltip-template accepts text or HTML. but when I pass some markup like

``html
  <h3>Stuff</h3>
  me <br>
 me <br>
``

it just renders as is. How can I pass an html snippet into tooltip-template?

**Comment by wouldgo** [comment]
Hi @cecilphillip,

In index.hml I added an example for what you are asking for.
The result should be like this:

![html-in-template](https://cloud.githubusercontent.com/assets/1098882/11615930/d3a87248-9c6d-11e5-8caf-24e49dedc6b1.png)

Hope this helps.
Dario

**Comment by cecilphillip** [comment]
Hi Dario, sorry for leaving this detail out.

My template is coming from a property on my scope. So when it looks like this:
```Javascript
 $scope.template = '<br>me <br> me again ..'
```
```html
  tooltip-template='{{ template }}'
```
the markup gets compiled as a string and not rendered as html. For my use case, I only need to binding the happen once, so no need for dirty checking.

**Comment by wouldgo** [comment]
Hi Cecil,

I've done some tests and I can not reproduce the issue (in the meantime I changed some important things that I did wrong). Could you try with the `1.0.5` version (published in npm)?

**Comment by cecilphillip** [comment]
@wouldgo updated to 1.0.5 and it works now. Thanks!!
