### ISSUE TITLE
element focus as show trigger doesn't work

### ISSUE THREAD

**Issue by gvuyk** [720kb/angular-tooltips#124]
these don't work:
```
tooltip-show-trigger="focus"
tooltip-show-trigger="onfocus"
tooltip-show-trigger="onFocus"
```

same for the 'blur' event. 
Bug or I'm missing something?

**Comment by gvuyk** [comment]
Ok, angular uses `element.on()` from jQuery wich seems to require the `focusin` and `focusout` events for focus and blur, and these 2 aren't available on firefox (all other major browsers support it)
Bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=687787
Reported on 2011 lol

**Comment by wouldgo** [comment]
Hi @gvuyk,

thank for your investigation (I really don't know the missing events on Firefox) and thanks for the polyfills, I star them just in case I enconter this issue.

Best regards,
Dario
