### ISSUE TITLE
Interference with ng-model

### ISSUE THREAD

**Issue by gvuyk** [720kb/angular-tooltips#125]
When adding tooltips to an ```<input>```, the model isn't updated 
**Fiddle:** http://jsfiddle.net/05Ljxhyd/

Tested with a ```<select>``` too but thats another story

Will investigate further later

**Comment by wouldgo** [comment]
Hi again @gvuyk,
I think that the problem you spot is the same as @jaymanned spots in #110. I've modified the whole approach for tooltip creation now and I'm asking you to retry with the actual master branch implementation.

Thank you
Dario

**Comment by wouldgo** [comment]
Ah! I saw only now the fiddle and it does not work... checking this...

**Comment by wouldgo** [comment]
There's a problem in directive priority. ngModel now is evaluated first then the directive.

**Comment by wouldgo** [comment]
I just released the `1.0.5` version with the fix for working with `ngModel` directive.

**Comment by gvuyk** [comment]
Working great now, thanks :)
