### ISSUE TITLE
./src/lib/angular-tooltips in index.js should point to ./lib/angular-tooltips

### ISSUE THREAD

**Issue by bayy** [720kb/angular-tooltips#126]
Ver 1.0.3 (even though the latest version on Github is 1.0.4, and npm install gives me ver 1.0.3)

I installed angular-tooltips using npm. After I included it in angular, I got an error saying ./src/lib/angular-tooltips did not exist (from index.js). After I changed it to ./lib/angular-tooltips, it worked.

**Comment by bayy** [comment]
I installed angular-tooltips using npm. After I included it in angular, I got an error saying ./src/lib/angular-tooltips did not exist (from index.js). After I changed it to ./lib/angular-tooltips, it worked.

**Comment by wouldgo** [comment]
Hi @bayy,

this was a typo during the refactor from 0.x.x to 1.x.x.
Now it's correct; could you please double check with master prior to release (and also publish :smile:) a brand new version?

Thanks,
Dario.

**Comment by bayy** [comment]
I see you have checked in your fix. However, 
'npm install angular-tooltips --save-dev' on my machine still gives me the old stuff (wrong path ./src/lib in index.js, ver 1.0.3)

**Comment by wouldgo** [comment]
Yes,
I'm asking you to use the master directly for testing purpose. I haven't publish anything yet.

**Comment by bayy** [comment]
The master branch works on my machine after I copy + paste it into my node_modules/angular-tooltips.

**Comment by wouldgo** [comment]
Thank you very much. I'm going to publish a new version as soon as I can (right now I'm not on my computer).

**Comment by bayy** [comment]
That will be great. Thanks.

**Comment by wouldgo** [comment]
version 1.0.5 contains the latest commits, including the `index.js` correction.

**Comment by wouldgo** [comment]
Closing, open again if there are problems.
