### ISSUE TITLE
Does angular-tooltips conflict with ng-click?

### ISSUE THREAD

**Issue by yulin-dong** [720kb/angular-tooltips#127]
I have ng-click on some elements. Once I add tooltips into these elements, the ng-click function is not called when I click on the element. I have tooltip-show-trigger="mouseover".

Thanks

**Comment by wouldgo** [comment]
Hi,

I've put an example of ng-click. I think that the main issue is in the version. Try with the just released 1.0.5 version.

**Comment by wouldgo** [comment]
Closing.
