### ISSUE TITLE
Z-index issue with 1.0.5 when tooltip in container with overflow:hidden

### ISSUE THREAD

**Issue by kotmatpockuh** [720kb/angular-tooltips#128]
When i have 

```
<div style="overflow:hidden;"></div>
```

and there i have input:

```
<input type="text" tooltip-template="{{ 'CLICK_TO_EDIT' : '' | translate}}" tooltips tooltip-side="bottom" tooltip-size="small" tooltip-speed="300">
```

tooltip is shrinked:

http://i.imgur.com/SY4fN3T.png

**Comment by wouldgo** [comment]
Hi @kotmatpockuh,

just to have a full example, could you please provide a codepen/jsfiddle/jsbin with the evidence for the issue you report.

Thanks
Dario

**Comment by kotmatpockuh** [comment]
@wouldgo maybe U have some fiddle with installed plugin, so i can change it a little bit?

**Comment by wouldgo** [comment]
Here you have a jsbin with all the things (this come from the ng-click example here in repo):

http://jsbin.com/tarihofexa/edit

**Comment by kotmatpockuh** [comment]
@wouldgo here it is: http://jsbin.com/ruwuvijici/1/edit?html,css,js,output

http://i.imgur.com/oGcjUVP.png

**Comment by wouldgo** [comment]
Hi again @kotmatpockuh,
we have right now released the implementation of the `tooltip-append-to-body` attribute that resolve your issue.
I've modified the jsbin, as you can se [here](http://jsbin.com/zizilizoni/edit?html,css,js,output).

We're going to make a new version that bring this new feature.
Best regards
Dario.

**Comment by wouldgo** [comment]
version 1.0.6 is realeased.

**Comment by wouldgo** [comment]
If there are other problems related to this issue do not hesitate to reopen.

Thanks for the snippet and have great sunday.
