### ISSUE TITLE
Tooltips conflict with UI Bootstrap 

### ISSUE THREAD

**Issue by hoodlem** [720kb/angular-tooltips#129]
When including https://angular-ui.github.io/bootstrap/ angularjs bootstrap, 720kb tooltips conflict with ui-bootstrap tooltips.

**Comment by wouldgo** [comment]
We know that ui-bootstrap provides a tooltip functionality as well and probably conflicts due to the name. We think that, if one developer includes all the ui-bootstrap library inside his page, he doesn't need to import another tooltip implementation.

For this reason I'm going to close this ticket.
Have a great day

Dario

**Comment by dmitriynosenko** [comment]
That's really great that you think in this way... For example:
1. I am using bootstrap via bower, so I don't have a solution how to disable his components
2. Tooltip in bootstrap works not good at all.
So is it so hard to add a prefix to make your directives unique?

**Comment by 45kb** [comment]
@dmitriynosenko hi, we already discussed this many times, if bootstrap doesn't allow to install third parties modules and/or does not allow to disable its own directives, well... it's really not our problem, because, first of all, they do not own any right on dirctives naming.

**Comment by dmitriynosenko** [comment]
Hi @45kb. In same time author of this lib doesn't have rights for directives names :)

**Comment by 45kb** [comment]
So who's gonna win? :)

I mean, my suggestion would be, go to bootstrap-ui and ask why you can't uninstall the directive.

**Comment by dmitriynosenko** [comment]
@45kb interesting question :)
I think the best and simple solution is to use prefixes for any custom component.
For example in last version of AngularUI they use prefix ```uib-...```.
In same time seems like they still support old name which conflicts with angular-tooltips.
So adding prefix it's a small and simple step and in same time it will work with or without any other lib.
Sure there is small change to have same prefixes for multiple libs, but I believe that this change is really small.
