### ISSUE TITLE
Sass and LESS

### ISSUE THREAD

**Issue by liviuignat** [720kb/angular-tooltips#13]
Sass and LESS integration would be nice, with some variables that can be changed from outside.

**Comment by 45kb** [comment]
Hi @liviuignat this is a great feature!

At the moment we can't work on this cause of other urgencies,
if you can and would help on this project we will be much glad!

**Comment by liviuignat** [comment]
Hi @45kb,

Ok, I will make the required changes for less.

Cheers,

**Comment by 45kb** [comment]
@liviuignat  We'll be grateful, thank you a lot for your time!

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case.

This is the only reason why i am going to close this issue.

Thank you and feel free to ask if any doubt or question about the new version.

**Comment by 45kb** [comment]
new module version also include SASS file
