### ISSUE TITLE
Not working on dynamically created elements

### ISSUE THREAD

**Issue by moh-abk** [720kb/angular-tooltips#133]
Hi, I'm trying to use this tooltip on elements I'm creating using `php` `echo` but it's not working and giving some weird effects.

Below is a sample of my code.

`echo '<li class="animated-class" ng-if="hasBasket()">
<a ng-href="http://www.example.co.uk/search-menu/{{cartItems[0].restaurant_id}}/{{cart[0].restaurant_name}}" 
id="signup-nav">
<i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;&#8358;{{(calcTotal())}}</a></li>';`

I've tried adding it in the above code and nothing works,

**Comment by gvuyk** [comment]
I dont think you should be creating elements with php (isn't that a main point of angular?), but anyways, post a jsfiddle so other people can see the problem

**Comment by 45kb** [comment]
@moh-abk Looks like you don't call the directive , where is the `tooltips` attribute?

PHP should really not be a problem since Javascript is run after, please provide a fiddle if you can as @gvuyk  suggested.

Thank you.

**Comment by moh-abk** [comment]
@45kb This is just a snippet of my code to show you where I'm adding all the directives

**Comment by WeKyle** [comment]
@moh-abk it'd be easier to diagnose what your issue is if you showed us where you're using the tooltips :smiley: 

I assume all the other angular things that your PHP generates work as intended?

**Comment by wouldgo** [comment]
Closing because issuer inactivity.
