### ISSUE TITLE
DOM Node - Memory Leak

### ISSUE THREAD

**Issue by theframework** [720kb/angular-tooltips#136]
Hi,

Love the plugin... but unfortunately causes my application to leak dom nodes... any ideas?

Thanks

**Comment by wouldgo** [comment]
Could you please articulate your issue? 

We need at least a snippet to understand what happens and where is the leakage. How do you measure it?

Waiting for inputs,
Thanks

Dario.

**Comment by wouldgo** [comment]
Closing by now, need some evidences for this kind of investigation.

**Comment by theframework** [comment]
![screen shot 2016-02-23 at 17 23 40](https://cloud.githubusercontent.com/assets/3763158/13260172/433db3bc-da52-11e5-8820-9c147a40766c.png)

**Comment by theframework** [comment]
![screen shot 2016-02-23 at 17 26 09](https://cloud.githubusercontent.com/assets/3763158/13260252/94b08bde-da52-11e5-8380-fdf97b431e60.png)

**Comment by theframework** [comment]
the first screen is when toggling between 2 pages in an SPA that has the tool tips. 

the second is toggling between the same 2 pages without the tool tips.  you cna see where i have forced garbage collection (i did the same on the first screen with the tooltips).

all the HTML i have for the tooltips is  (the load SVG just requests an SVG a appends teh file contents.)

<a class="info-button" tooltip-smart="true" tooltips tooltip-template="{{::text.tooltips.login.password}}">
        <load-svg class="icon" type="theme" name="info"></load-svg>
    </a>

There must be some reference which is not being cleared some how.... id love to use this plugin, it is great... just need to fix this issue

Any help/advice would be greatly appricated.

Thansk in advance

**Comment by theframework** [comment]
`<a class="info-button" tooltip-smart="true" tooltips tooltip-template="{{::text.tooltips.login.password}}">
        <load-svg class="icon" type="theme" name="info"></load-svg>
    </a>`

**Comment by 45kb** [comment]
@theframework Hi, actually @wouldgo is not here in these days, i am sure he will reply you as soon as he's back.

Thanks.
