### ISSUE TITLE
Tool tip set to opacity:0 but not removed from DOM after fade out.

### ISSUE THREAD

**Issue by nicolaslair** [720kb/angular-tooltips#140]
Hi all,

I have a bug where after a fade out, the div created by the tooltip is not removed from the DOM, so I can't click on any buttons displayed behind it. See attached image for an example. When inspecting the corresponding div, I see that the opacity is set to 0, but display is not switched to none. Is there an option to simply force removing the div from the DOM after a fade out? I use angular-tooltips 0.1.22

Thanks in advance,

Nico

![screen shot 2016-02-04 at 6 31 16 pm](https://cloud.githubusercontent.com/assets/667979/12828442/29d2c3da-cb85-11e5-9b09-1aa76ceff7d8.png)

**Comment by nicolaslair** [comment]
More info: the problem is happening because on fade out, only the 'visible' property is updated. Or it only defines the visibility of the element (like saying opacity: 0), and it's still selectable, clickable, and whatever it used to be; it's just not visible. So to fix it I updated my custom CSS to include the following:
`
._720kb-tooltip {
   pointer-events: none;
}
`

**Comment by 45kb** [comment]
@nicolaslair  Hi, if you are using the 0.1.22 version of the module i really suggest you to give a try always at the latest version/release.

Another way could be to use `z-index:-1;` probably
However, glad if you found a fix :+1:
