### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by theframework** [720kb/angular-tooltips#143]
Hi  please see closed issue #136  i have replied to your questions.

**Comment by theframework** [comment]
HI,

Following on from the noted issue... i think i may have found the cause...


the is a window.addEventListener('resize', resize); which get applied each time a toll tip is used.

However it does not look like it gets removed.

Ive chnaged the code as below....


`'add': function add(callback) {

				if (!callbacks.length) {

					window.addEventListener('resize', resize);
				}
				addCallback(callback);
			},`
to 
`return {
			'add': function add(callback) {

				if (!callbacks.length) {

					window.addEventListener('resize', resize);
				}
				addCallback(callback);
			},
			'remove': function remove(callback) {

				if (!callbacks.length) {

					window.removeEventListener('resize', resize);
				}
				removeCallback(callback);
			}
		}`



then in the Destroy method  resizeObserver.remove()

Seems to help... can you advise?

**Comment by 45kb** [comment]
Seems working much better now, i am going to close

Big thanks to @Omer

If any other doubt or problem feel free to ask in here.
