### ISSUE TITLE
Tooltip doesn't close on mouse leave, if the DOM element is clicked.

### ISSUE THREAD

**Issue by shishir99111** [720kb/angular-tooltips#144]
we are having the execution as follows:
onclick of 'label' , pop-up window opens up as well as the tool-tip.
but tooltip doesn't on after mouse out event

**Comment by 45kb** [comment]
Hi @shishir99111 can you please provide a jsfiddle or plnkr, i was trying replicating the issue but i am not sure if i quite understand it.
