### ISSUE TITLE
Tooltip changes layout of parent

### ISSUE THREAD

**Issue by focomoso** [720kb/angular-tooltips#145]
I haven't dived deeply into what's going on, but when I add a tooltip to an icon in my app, it seems to be changing the vertical alignment of the icon. 

The middle refresh button has a tooltip on it while the one on the right doesn't:
![screen shot 2016-03-09 at 9 45 34 am](https://cloud.githubusercontent.com/assets/9621822/13644652/c83ff248-e5db-11e5-814c-53f2118cc734.png)

Any thoughts?

**Comment by 45kb** [comment]
Hi, what's your HTML structure?

Have you tried something like:

`<span tooltips><i>icon</i></span>`

If you are using `<i>` they look famous for bad behaviors like the one you described.

**Comment by focomoso** [comment]
I got it to work by fiddling with the css, thanks.

**Comment by 45kb** [comment]
You're welcome!
