### ISSUE TITLE
tooltipDirective is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by robinsving** [720kb/angular-tooltips#146]
Trying to run angular-tooltips in strict mode `<html lang="en" ng-app="myapp" ng-strict-di>` causes the following error message on version 1.0.7
```
"Error: [$injector:strictdi] tooltipDirective is not using explicit annotation
and cannot be invoked in strict mode
http://errors.angularjs.org/1.5.0/$injector/strictdi?p0=tooltipDirective
```

**Comment by robinsving** [comment]
Using webpack to require this when I see the problem. 
Seems weird that this happens. Using the minified version works for me.

**Comment by 45kb** [comment]
@robinsving thanks will investigate this, if you find what's happening please let know!
