### ISSUE TITLE
Tooltips with ng-if

### ISSUE THREAD

**Issue by focomoso** [720kb/angular-tooltips#148]
I've been chasing down an issue for a day now and I think I've figured out what's going on.

If I add a tooltip to an element that's not in the dom on page load because of an ng-if="false", but later switch the ng-if to "true" the tooltip never shows because the linkingFunction is never called. At least I think that's what's going on. Are people generally able to add tips to elements that aren't in the dom on load?

**Comment by 45kb** [comment]
Hi, this sounds very strange, however, have you already tried using ng-if outside of the tooltip element?

Something like:

```html
<span ng-if=""><a tooltip>Tooltip</a></span>```
