### ISSUE TITLE
Add support for Angular 1.5.x

### ISSUE THREAD

**Issue by artdias90** [720kb/angular-tooltips#149]
Any reason why this is still tight to angular.1.4.7?

**Comment by 45kb** [comment]
@artdias90  Hi, i guess you can install any ng version you want separated, not?

No reasons for a specific angular version, we just need to make some tests using a newer version and update it.

**Comment by artdias90** [comment]
Im not expert with bower so i always have to manually set a resolution  since im using angular 1.5 . Then this was was breaking my automated tests on circleCI. But modifying bowr.json from tooltip solved the issue.

**Comment by hitolaus** [comment]
This is a really annoying problem. 
I have had to add ignore dependency on angular-tooltip to avoid breaking the build and the other developers now have to manually add angular-tooltip

**Comment by artdias90** [comment]
+1, please fix

**Comment by 45kb** [comment]
Hi, this could be `"angular": "~1.*.*"`  correct for you ?

**Comment by artdias90** [comment]
^1.x.x
,  so that 1.x.x is the minimum version required.

**Comment by 45kb** [comment]
ok, and , sorry for asking this, but i never got into such troubles, do you need a new release of the module ?

**Comment by artdias90** [comment]
right now i dont need it, should I open an issue then?

**Comment by hitolaus** [comment]
I would like a new release, so that I can remove the ignoreDependency :-)

**Comment by 45kb** [comment]
Ok guys, will do a new release in a while, thanks.

**Comment by 45kb** [comment]
Done https://github.com/720kb/angular-tooltips/releases/tag/1.0.9

**Comment by artdias90** [comment]
much appreciated
