### ISSUE TITLE
Does it not using $templateCache?

### ISSUE THREAD

**Issue by slavafomin** [720kb/angular-tooltips#151]
Hello!

Thank you for this great library!

I'm trying to load the template from Angular's [$templateCache](https://docs.angularjs.org/api/ng/service/$templateCache) service, however, it's still trying to load it from URL. Does it not respect `$templateCache`?

Thanks!

**Comment by 45kb** [comment]
Please let know if you can make changes to the PR as we discussed here: https://github.com/720kb/angular-tooltips/pull/152

Thank you a lot for your time 💯

**Comment by 45kb** [comment]
https://github.com/720kb/angular-tooltips/issues/168
