### ISSUE TITLE
Regression of bug #19

### ISSUE THREAD

**Issue by xlegs** [720kb/angular-tooltips#156]
v1.0.9 displays blank tooltips when the model is blank. Eg:
`<div tooltips tooltip-template=""></div>`
renders an empty tooltip.

The is a regression of bug #19

**Comment by 45kb** [comment]
Thanks for reporting this, updating to 1.0.10 should solve the problem definitely https://github.com/720kb/angular-tooltips/releases/tag/1.0.10

**Comment by xlegs** [comment]
That did it! Thanks!
