### ISSUE TITLE
Show/hide tooltip on same event (tooltip triggers)

### ISSUE THREAD

**Issue by pavlosadovyi** [720kb/angular-tooltips#161]
I want to make tooltip mobile friendly, I mean if you click on element first time - tooltip is appeared and stay open until got the second click on self or another tooltipped element?
I already tried to pass click event to both options:

``` html
tooltip-show-trigger="click" tooltip-hide-trigger="click"
```

But it seems that it's open and close immediately. Is it possible to reach behavior described above with options?
Thanks in advance!

**Comment by 45kb** [comment]
Does this works on desktop?

For mobile you should use touch events instead of mouseevents

Try `tooltip-hide-trigger="touchstart"` for example

**Comment by pavlosadovyi** [comment]
Ok, for mobile this works.
```html
tooltip-hide-trigger="touchstart"
```
When I tap: cursor moves and it works like hover so tooltip is show up. When I tap once again on the same element tooltip will close. But when I tap on another element with tooltips attribute it won't close previous one.

But how can I reach the same functionality on desktop. I mean open on click and close on click also?
Thank you for response!

**Comment by 45kb** [comment]
I was curious about it, indeed i was asking you if it works, and obviously it can't work, because click on show and click on hide will conflict.

I have no clue for the moment, we should implement a sort of switch for when you want to use same event both for hide and show.

Sorry for that, i will try something asap, or if you have some idea feel free to PR!

**Comment by pavlosadovyi** [comment]
If you point me in the code, I can try to implement it. It's quite big and I sure you have better understanding what's going on inside.

**Comment by 45kb** [comment]
Could be awesome if you help us.

Here is the tooltip show trigger event: https://github.com/720kb/angular-tooltips/blob/master/lib/angular-tooltips.js#L603

and here is the hide event: https://github.com/720kb/angular-tooltips/blob/master/lib/angular-tooltips.js#L615

**Comment by kunalnaik** [comment]
A possible work around is:
`tooltip-show-trigger="focusin" tooltip-hide-trigger="focusout"`

The tooltip will open when clicked, and close whenever some other element is clicked (given focus). I have yet to test this on mobile however.

**Comment by guerson** [comment]
Hi team,
I really like this plugin. Now, i need to do something specific about the Show/Hide Events.

Is there a way to open tooltips by a conditional expression and i need it to remain open ?

```
 <a href="#" 
tooltips tooltip-close-button="true"
tooltip-side="top"
tooltip-template="tooltip text"
tooltip-class="tooltip-danger"
tooltip-hidden="false"
tooltip-show-trigger="touchstart">
            Tooltip text here
        </a>
```
I need something like :
```<a href="#" tooltip-show="{{1 == 1}}">Example</a>```
