### ISSUE TITLE
Tooltip position following mouse

### ISSUE THREAD

**Issue by ArsenyYankovsky** [720kb/angular-tooltips#167]
Hey guys.

I have a long progress bar and I want my tooltip to appear on the exact position of a mouse. Right now it always appears above the middle of the progress bar.

```
<div class="max-width" tooltips tooltip-template="{{vm.tooltipProgress}}">
    <md-progress-linear md-mode="determinate" ng-value="vm.progressPercent">
    </md-progress-linear>
</div>
```

I tried updating styles of `tip` element in the `ng-mousemove` handler but it doesn't help for some reason.
Any way to achieve this?

Thanks in advance.

**Comment by 45kb** [comment]
@ArsenyYankovsky Hi, my suggestion is to use a simple css tooltip, will be not so easy to achieve what you want, just look for https://www.google.com/?q=pure+css+tooltip 👍
