### ISSUE TITLE
Use $templateCache for loading templates

### ISSUE THREAD

**Issue by eekboom** [720kb/angular-tooltips#168]
We tried to use "ng-repeat" inside a tooltip's template.
That did not work and we needed a while to find out that the template specified via "tooltip-template" seems to not get compiled.
When we switched to "tooltip-template-url", we at first got 404s when the app tried to load that single template. Our build system uses grunt-angular-templates to put all template in a single js file that pre-populates the template cache.
Only after we copied all "*-tooltip-template.html" to the output build did it started to work (including the "ng-repeat").

So please check if any templateUrl is present in the cache already and only load it if it isn't found there (and then fill the cache after loading).

**Comment by gbruins** [comment]
+1
Just ran into this issue as well.  Fairly critical issue, in my opinion, as any serious app will be caching it's templates

**Comment by ruisilva450** [comment]
Sorry to ask but is this solved or not?

**Comment by 45kb** [comment]
@ruisilva450 hi, it isn't solved, the issue is still open :)
