### ISSUE TITLE
Complex logic as ToolTip on the Angular UI Grid's cellTemplate

### ISSUE THREAD

**Issue by Sampath-Lokuge** [720kb/angular-tooltips#171]
Hi,

I'm using Angular UI-Grid.This is the grid implementation.

**JS**

```
var statusCellTemplate =
    '<div class="ui-grid-cell-contents"><span ng-
if="row.entity.statusDetails.length>=2" title="My Tooltip">[Multiple Statuses]
    </span></span></div>';

vm.propertyListGridOptions = {
                appScopeProvider: vm,
                flatEntityAccess: false,
                fastWatch: true,
                showHeader: false,
                columnDefs: [
                    {
                        name: app.localize('ListingStatus'),
                        cellTemplate: statusCellTemplate,
                        width: 240,
                    },
                 ],
                data: []
            };
```
I need to show the ToolTip by using below logic.Can you tell me how to implement such a logic with the above cellTemplate by using your Tooltip directive ?

```
_.each(row.entity.statusDetails, function (s) {
                            vm.statusValues += s.status.name + ', ';
                        });
```

Note : `_.each` can be a `ng-repeat` on angular.

**Comment by 45kb** [comment]
Hi @Sampath-Lokuge  you can use tooltip-view-controller="" which is missing in the README sorry for that,

something like:

```html
<span tooltips
        tooltip-template-url="demo/views/index-without-embedded-controller.html"
        tooltip-controller="Ctrl as ctrl">
      </span>
```

**Comment by Sampath-Lokuge** [comment]
Thanks a lot @45kb. Your Tool-tip directive seems to be very powerful one.But the README is not like that.That is pretty disappointing.Hope you'll add those amazing features also into the README soon.

I need further help from you.Hope you'll give it to me.I need to create my Tooltip template as shown below.Could you provide another step or two further in addition to the one you have provided above to achieve my requirement.Thanks.

```
<script type="text/ng-template" id="myTooltipTemplate.html">
    <span ng-repeat='status in row.entity.statusDetails'>{{status.name}}<br /></span>
 </script>  
```

**Comment by 45kb** [comment]
`tooltips` is a directive, just put it in the html where you want to use it.... :)
