### ISSUE TITLE
how to use show triggers?

### ISSUE THREAD

**Issue by ironchef1369** [720kb/angular-tooltips#183]
I've got a $rootScope.$broadcast('testEvent'); happening that I'm trying to the the tooltip show up on, but I'm not having much luck getting the directive to be listening.  Am I thinking that the listener setup on the tooltip doesn't work in that way?

I set the tooltip-show-trigger="testEvent mouseover" and anticipated it showing up when the broadcast was called, but its not doing so.  

Any ideas?

**Comment by 45kb** [comment]
Hi @ironchef1369 the trigger listen to mousevents not events you launch.

My suggestion would be to trigger mouseover or click on tooltip when your event is launched.
