### ISSUE TITLE
Sass::SyntaxError: Invalid CSS after "tooltip ": expected keyframes selector, was "0%"

### ISSUE THREAD

**Issue by solutionize-rameshkumar** [720kb/angular-tooltips#184]
Getting errror on rails assert pre-compile 

![rails assert pre compile error](https://cloud.githubusercontent.com/assets/17652419/19180532/19a7f212-8c84-11e6-9903-0b0229bcfebd.png)

**Comment by celsomtrindade** [comment]
This is caused by this piece of code in the css file:

    @-ms-keyframes animate-tooltip {
        tooltip 0% {
            opacity: 0;
        }
        tooltip 50% {
            opacity: .5;
        }
        tooltip 60% {
            opacity: .8;
        }
        tooltip 70% {
            opacity: .9;
        }
        tooltip 90% {
            opacity: 1;
        }
    }

I believe this should be like this:

    @-ms-keyframes animate-tooltip {
        0% {
            opacity: 0;
        }
        50% {
            opacity: .5;
        }
        60% {
            opacity: .8;
        }
        70% {
            opacity: .9;
        }
        90% {
            opacity: 1;
        }
    }

**Comment by 45kb** [comment]
Hi, thanks for spotting out this, just update to 1.1.8 version and you should be fine with this. 👍
