### ISSUE TITLE
Proper module export, instead of the '720kb.tooltips' string

### ISSUE THREAD

**Issue by KatFishSnake** [720kb/angular-tooltips#186]
Currently we use ES6 import syntax to get the modules we need for our main app
its very convenient as we can name them however we want:

![screen shot 2016-11-22 at 6 37 02 pm](https://cloud.githubusercontent.com/assets/12003520/20549590/b1ea2be4-b0e2-11e6-909a-97b91ba4663b.png)

and to utilize similar syntax for non-module exporting packages we have to hack around with conditionals like this:

![screen shot 2016-11-22 at 6 39 49 pm](https://cloud.githubusercontent.com/assets/12003520/20549629/186db7fa-b0e3-11e6-8442-0eac4feef849.png)

so can you please address it and properly export module.
I would think even simple
```
require('./dist/angular-tooltips');
module.exports = '720kb.tooltips';
```
would work

**Comment by 45kb** [comment]
Hi @KatFishSnake this https://github.com/720kb/angular-tooltips/blob/master/index.js doesn't work?

**Comment by KatFishSnake** [comment]
Oghhh, thats right, thanks a lot, really not sure what was wrong before, worked on second try
