### ISSUE TITLE
popover position auto option not available 

### ISSUE THREAD

**Issue by Muralikrish511** [720kb/angular-tooltips#187]
I think it's a great feature if you add auto position option to pop over when there is not enough space on right/left/top/bottom its must be shown where ever its find a free space . 

Added a link to understand expected behaviour ( http://www.a2zwebhelp.com/bootstrap-tooltips ) .

**Comment by 45kb** [comment]
Hi @Muralikrish511 you can use tooltip-smart for that see https://github.com/720kb/angular-tooltips#doc
