### ISSUE TITLE
Show only if non-empty content

### ISSUE THREAD

**Issue by danmichaelo** [720kb/angular-tooltips#19]
This module is great. The only thing I'm missing is some way to show the tooltip only if some criteria is met. What about having

    <span tooltip-content="{{ data.comment }}"></span>

show a tooltip only if `data.comment` does not evaluate to false (blank/undefined, ...)?

**Comment by 45kb** [comment]
Hi @danmichaelo  have you tried anything for it? I think the same expression watcher should be both on tooltip-title and tooltip-content ... and looks easy to do, let me know, thank you a lot.

**Comment by 45kb** [comment]
@danmichaelo Hi, i introduced a little control over title and content so if tooltip is empty it will not init, if you can please try it and feel free to report any issue or further needs.

Thanks for your suggestion!

**Comment by danmichaelo** [comment]
Cool, thanks for fixing it so quickly! Tested it now, and it works great :+1:

**Comment by 45kb** [comment]
@danmichaelo going to release a new version so, thanks to you really!
