### ISSUE TITLE
[W3C]Page not validated if a tooltip is used

### ISSUE THREAD

**Issue by simonepri** [720kb/angular-tooltips#191]
![image](https://cloud.githubusercontent.com/assets/3505087/21293348/c879dc44-c521-11e6-8be8-edea6b4e4380.png)

This is the incriminated line:
https://github.com/720kb/angular-tooltips/blob/master/dist/angular-tooltips.js#L760

I saw that that ID is not used for anything so I think it can simply be removed or replaced by:

`closeButtonElement.addClass('close-button');`

**Comment by 45kb** [comment]
@simonepri yes that should be removed probably that's the reason why close button is no more working....

**Comment by 45kb** [comment]
https://github.com/720kb/angular-tooltips/pull/193
