### ISSUE TITLE
Hide tooltips for touchscreen

### ISSUE THREAD

**Issue by mbirnbaum** [720kb/angular-tooltips#192]
I only want my tooltips to show with mouse interactions. If it is a touch screen, I do not want it to show.
The default show-trigger is `mouseover`. But this is also showing the tooltips when I touch. What setting should I use to disable tooltips on touchscreen?

**Comment by 45kb** [comment]
@mbirnbaum tooltip-hide-trigger="touchend" and `tooltip-show-trigger="touchstart"` i believe

**Comment by mbirnbaum** [comment]
Where would I add this? in the `tooltipsConfProvider`?

**Comment by 45kb** [comment]
@mbirnbaum Controller and view

**Comment by mbirnbaum** [comment]
But, I use the tooltips all over my app. There's no global setting for this?

**Comment by 45kb** [comment]
You can but if you add it to the config provider it will be the same both for touch and normal screens

I'd make a little global find&replace in view files.

**Comment by 45kb** [comment]
@mbirnbaum try also `tooltip-hide-trigger="touchstart dbclick"`

**Comment by mbirnbaum** [comment]
`tooltip-hide-trigger="touchstart dbclick"` does nothing. showing tooltips on iPad.

**Comment by 45kb** [comment]
you can even use css to show or hide tooltips, just hack around and/or use tooltip-hidden nope?
