### ISSUE TITLE
img as template?

### ISSUE THREAD

**Issue by eaba** [720kb/angular-tooltips#195]
Hello is it possible to do something like this:
`tooltip-template="<img src="data:image/jpg;base64,' + data[y]['Image'] + '" />"`
I have tried it but it is not working!

**Comment by 45kb** [comment]
Hi for html you can use `tooltip-template-url="path/to/template.html"`

**Comment by eaba** [comment]
In other words, what I desire to achieve is not possible right?

**Comment by 45kb** [comment]
@eaba have you tried it ? :)

maybe: 

```tooltip-template="<img src="data:image/jpg;base64,{{data[y]['Image']}}" />"```

Just try it. I think it should work.
However the best practice is to use an external view for html templates.

**Comment by eaba** [comment]
I tried it and i got something like this instead `<a tooltip-smart="true"`
The anchor was not being handled properly so i think
