### ISSUE TITLE
QUESTION: Is there a reason why the element is wrapped in to custom DOM elements?

### ISSUE THREAD

**Issue by tiblu** [720kb/angular-tooltips#196]
**Question**

Is there a specific reason why the implementation wraps the target element into custom HTML elements (``<tooltip><tip-cont>...``) instead of adding the custom elements to the ``<body>`` when the tip is to be displayed?

Code:

`<a href="#" tooltips tooltip-template="Link tooltip" tooltip-smart="true">Link</a>`

Result:

```
<tooltip tooltips="" tooltip-template="Link tooltip" tooltip-smart="true" class="tooltips _steady _ready _top"> 
    <tip-cont> 
        <a href="#">Link</a> 
    </tip-cont> 
    <tip class=""> 
        <tip-tip> 
            <span id="close-button" style="display: none;">×</span> Link tooltip 
        </tip-tip> 
        <tip-arrow></tip-arrow>
    </tip> 
</tooltip>
```

**Problem**

Wrapping like this changes DOM which may cause layout issues when CSS child selectors are used and also because of default for each element is ``display: block``.

**Alternative**

Add all the tooltip DOM elements to ``<body>`` and not wrap original element.

**Comment by 45kb** [comment]
Hi @tiblu custom tags are the only way possible for not to inherit your CSS rules inside tooltip CSS

**Comment by tiblu** [comment]
@45kb Thank you for your quick explanation and all the work on this project!

**Comment by 45kb** [comment]
@tiblu you're welcome ;)
