### ISSUE TITLE
doesnt work with safari and firefox

### ISSUE THREAD

**Issue by NisanurBulut** [720kb/angular-tooltips#200]
hi I installed angular-tooltips and ı inserted on  the app.js **it is working on the chrome properly** but if ı inserted , '720kb.tooltips' on the app module ; my web site doesnt load on the firefox and safari..

**Comment by coopernewby** [comment]
I get the same issue with a /dist/angular-tooltips.js.map

**Comment by coopernewby** [comment]
short term work around that fixed this error is using the non minified js file. Might be an error with mapping the file. 

require('angular-tooltips/dist/angular-tooltips.js')

**Comment by 45kb** [comment]
Are you sure you are including the correct files and installing it properly?

I see it works even with angular 1.6.0, just follow this demo page: https://github.com/720kb/angular-tooltips/blob/master/index.html

PS: you don't have to include .map files, .map files are recognized by the browser itself.
