### ISSUE TITLE
Long text!

### ISSUE THREAD

**Issue by eaba** [720kb/angular-tooltips#207]
I have a long text for the template content. I am experiencing an issue where only about 90 characters are shown while the rest are hidden.

How can I fix this?
Thanks

**Comment by 45kb** [comment]
Is the text with no white spaces i image @eaba ?
You could use a custom tooltip class `tooltip-class="my-class"`
```
//CSS
 .my-class tip-tip{word-break: break-all;}
```

should do the job.

It's all html and css you can work around this easily.

**Comment by eaba** [comment]
> Is the text with no white spaces i image @eaba ?

@45kb I did get that! My text has whitespaces if that what you meant and is that the work around?

**Comment by 45kb** [comment]
@eaba just if text is really long you can adjust it with a custom tooltip class and custom css very easily 👍

**Comment by eaba** [comment]
Okay thanks. I will give it a try!

**Comment by eaba** [comment]
Hello @45kb that does not seem to work. I have also directly modified the tip-tip style no result.

**Comment by 45kb** [comment]
@eaba send me a jsfiddle i'll help you

**Comment by eaba** [comment]
Its a large web app.........and the elements with tooltips are dynamically generated...jsfiddle might not be a possibility.

**Comment by 45kb** [comment]
@eaba i meant just create a jsfiddle with tooltips and <your_text_inside_tooltip> that would be enough.

**Comment by eaba** [comment]
@45kb I got you.....just that am on limited time to create a jsfiddle right now. Just so you know, the tooltip worked perfectly for large text until your current release. That is versions where `tooltip-template` was `tooltip-content`

**Comment by eaba** [comment]
@45kb  finally got it to work. The issue was that the tooltip element inherited `white-space: nowrap;` rule from its parent, so that meant no matter I did the `word-break:break-all` rule had no effect with the parent rule being applied.

Thanks for your time!!
