### ISSUE TITLE
uib-tooltip issue-showing two tooltip at a time

### ISSUE THREAD

**Issue by Vikas-Kumar56** [720kb/angular-tooltips#209]
I am trying to change the current message of uib-tooltip in my directive but it creates a new tooltip and start displaying two tooltips at a time.
Here is the plunker demonstrating the issue.
https://plnkr.co/edit/Dk0VYxA6kb0w1hTDis11?p=preview
How can i change the message of uib-tooltip in my directive.

Thank in advance.

**Comment by 45kb** [comment]
@Vikas-Kumar56 you should ask the mantainers of uib-tooltip this is another project, i am afraid you posted in the wrong repo :D
