### ISSUE TITLE
when  tooltip-show="true" , Tootltip not hidden when hover on other items

### ISSUE THREAD

**Issue by SaffaShujah** [720kb/angular-tooltips#210]
When tooltip set to tooltip-show="true"
Tooltip does not hides when hover on other elements

Tooltip should hide when hover on other elements. can we do that ?

**Comment by 45kb** [comment]
@SaffaShujah tooltio-show="true" means it's always visible, you must remove the attribute or set it to FALSE if you want to hide it.

**Comment by SaffaShujah** [comment]
tooltip-hidden="" is this flag can be set dynamically?

**Comment by 45kb** [comment]
no just toggle tooltip-show="true/false" should do the job.

otherwise tooltips-show="true" then tooltip-hidden="true" to hide just playaround with them ;)
