### ISSUE TITLE
Tooltip template how to escape quotes?

### ISSUE THREAD

**Issue by deepank411** [720kb/angular-tooltips#211]
I enclosed the tooltip-template with single quotes and used double quotes inside to assign classes to the HTML tags, but in the span tag I have to conditionally add a class that has to be within quotes themselves according to angular syntax, which leads to an error on the page.
```
<span tooltips tooltip-side="bottom" tooltip-size="large" tooltip-class="t-tooltip" tooltip-template='
    <div>
        <span class="{{ detail.price_available == 1 ? 't-strikethrough' : ' '}}">NOT WORKING</span>
    </div>
'>
</span>
```

Is there some way to escape the single quotes inside the tooltip-template or any secondary quotes that can be used instead of the single quotes at that location. I have already tried using backticks and reverse slash to escape the single quote to no avail.

**Comment by 45kb** [comment]
@deepank411 You should use` tooltip-template-url="path/to/tooltip.html"` when you have logic in  your html.

Maybe you could try with angular $sanitize but i did not tried.

**Comment by deepank411** [comment]
using a relative path along with tooltip-template-url worked. Thanks!
