### ISSUE TITLE
HTML Tooltip disappears when moving mouse onto it

### ISSUE THREAD

**Issue by sh0ber** [720kb/angular-tooltips#212]
I have an HTML tooltip that consists of nothing but a link.  It is also triggered by a link.
After triggering the tooltip, I want to be able to move my mouse onto the tooltip to click the link in the tooltip, but it disappears as I am moving the mouse to it.  Here is a small GIF of the problem:

http://recordit.co/HLDULauArs

'6/12/2017' is a link I am trying to click (in the GIF).

**Comment by 45kb** [comment]
@sh0ber Hi, you should adjust tooltip-hide-trigger and tooltip-show-trigger to your needs.

**Comment by sh0ber** [comment]
Hi, thanks.  I've noticed those but there is no documentation so I am unsure how to proceed.  Do those properties only accept events from the tooltip's root element?  If so, there is no change I could make to suit my needs.  I need it to close when there is a mouseleave on the tooltip itself, not the root element.

**Comment by 45kb** [comment]
You can use both mouse and touch events relative to the window not to the parent.

**Comment by 45kb** [comment]
In your case it should be: 
`tooltip-show-trigger="click"`
`tooltip-hide-trigger="blur" `

i suppose!

however do some tests ;)

**Comment by sh0ber** [comment]
All I wanted is for the tooltip to stay open when my mouse is moving from the parent to the tooltip.  These events will not help with that (it is not a CSS/structure problem).  You can see in the GIF that it closes when I leave the parent.  Oh well, thank you anyway.

**Comment by sh0ber** [comment]
http://recordit.co/RDomXhxY1O

**Comment by 45kb** [comment]
@sh0ber that's the most standard and default scenario.... i don't see any bug actually.
If you want the tooltip to stay opened you need to override `tooltip-hide-trigger` with an event you desire.

**Comment by sh0ber** [comment]
I understand but I am discussing the HTML tooltip, not the basic default scenario.  The problem arises with an HTML tooltip with interactive content.  You will be unable to consistently interact with the content in the tooltip because it will be closed before you get to it.

Overriding hide will not help if you want to hide the tooltip upon leaving the tooltip since those events cannot be accessed.

**Comment by 45kb** [comment]
@sh0ber You're right, i mean could be great to listen also on tooltip events, but this is not possible atm.
If any gentleman would like to PR something for this it would be MUCH appreciated of course!

**Comment by 45kb** [comment]
@sh0ber one more work around could be to use tooltip-show="TRUE or FALSE" to toggle it when you want.

**Comment by sh0ber** [comment]
This workaround suffers from the same problem since the expression would need to be changed from the tooltip's mouseleave

**Comment by 45kb** [comment]
@sh0ber remember you could also have your own template inside the tooltip... you could bind events to your elements inside tooltip, however we must admit is not really the best way to achieve this :)
