### ISSUE TITLE
Tooltip not showing in Angular Modal

### ISSUE THREAD

**Issue by dilumn** [720kb/angular-tooltips#214]
I'm trying to add this tooltip directive inside an Angular Modal but it's not showing inside the modal. In a normal page it shows correctly but not in a modal.

**Comment by 45kb** [comment]
@dilumn hi, have you debugged a little? We can't fix angular modal if that's the problem...

Please be more specific, thanks 👍

**Comment by dilumn** [comment]
Here is the code I'm using inside my modal,

```
<div class="col-sm-2 col-md-2 col-lg-2 invoice-index-product-name">
  <a class="control-label overflow-text" tooltips tooltip-side="top" title="{{currentProduct.product_name}}">{{currentProduct.product_name}}</a>
</div>
```

This exact code is working in a normal html with `tooltips` directive. But not inside a modal

**Comment by 45kb** [comment]
@dilumn still not have sufficient informations, can you please create a live jsfiddle or plnkr with your code inside? I may try look what's happening :)

**Comment by dilumn** [comment]
The issue was with `._720kb-tooltip` style `z-index` & override that `z-index` with a higher value. So it's working fine. Thank you for your help.

**Comment by 45kb** [comment]
@dilumn glad that you solved, indeed, at the end the tooltip is made on top of css actually ;)
