### ISSUE TITLE
How to add depth to the tooltip with shadow?

### ISSUE THREAD

**Issue by koushikmln** [720kb/angular-tooltips#217]
Not able to add depth to the tip of the tooltip. Any examples for demo?

**Comment by 45kb** [comment]
@koushikmln what you mean by depth? z-index perhaps?

**Comment by koushikmln** [comment]
shadows actually. so im using a white background and want the tooltip also to be in white but with a shadow to differentiate. i was able to apply shadow to the box but the tip is a little off everytime i try.

**Comment by 45kb** [comment]
@koushikmln definitively not clear sorry, can you please create a jsfiddle or plnkr to show the problem?

thanks.

**Comment by koushikmln** [comment]
![image](https://user-images.githubusercontent.com/8670988/28026505-ed5f2da6-65b3-11e7-8b19-1541ff7377c7.png)

**Comment by koushikmln** [comment]
in the above pic i tried adding depth to the tooltip so that it is differentiated. was not able to do it for the tip. so i just greyed it out.

**Comment by 45kb** [comment]
oh ok got it, you must override the arrows style, look in the css file for this element https://github.com/720kb/angular-tooltips/blob/master/lib/angular-tooltips.scss#L171

and make it your own style 👍
