### ISSUE TITLE
How set dynamic tooltip title?

### ISSUE THREAD

**Issue by mbury** [720kb/angular-tooltips#22]
I want use tooltip with dynamic content set from controller variable but when I try something like this:
`tooltip-title="{{controller.message}}"`
two-way-binding not work. Tooltip show only first assign message text.

**Comment by 45kb** [comment]
Hi @mbury  you're right, sorry for that.

It just need the attr $observe and two way bindings will work, just give us sometime and we'll do that, or if you want to PR it we'll be much glad! 
thanks for reporting

**Comment by 45kb** [comment]
https://github.com/720kb/angular-tooltips/issues/23

**Comment by antonioreyna** [comment]
hello, how can i set my title dynamically? i am using this: ```tooltip-title="Click to copy {{email}}"```but it is not working, just shows click to copy text not the variable? thanks

**Comment by 45kb** [comment]
@antonioreyna  Hi at the moment looks not possible but they are making it https://github.com/720kb/angular-tooltips/pull/24
