### ISSUE TITLE
Allow for the same event to 'toggle' display of tooltips

### ISSUE THREAD

**Issue by JAndritsch** [720kb/angular-tooltips#29]
There doesn't appear to be way to allow the same event to be used to "toggle" the display of a tooltip. For example, consider what would happen when I configure the directive as follows:

  ```
<a href="#" tooltips="" tooltip-title="tip" tooltip-show-trigger="click" tooltip-hide-trigger="click" tooltip-side="left">Show tooltip on click and hide tooltip only on click</a>
```
I was hoping this would allow me to click on the link and see the tooltip show up, then be able to click on the link again to hide it (effectively toggling the display). From my testing, however, it does not appear to work that way because the 'click' event is being bound with two separate callbacks at the same time. 
So when I click on the link, both callbacks are fired immediately. This causes the tooltip to open and then close immediately after, sometimes even fast enough to where I can't see it.

It would be nice if we could specify a single event for both open and close actions that will behave as a toggle when invoked.

**Comment by 45kb** [comment]
Hi @JAndritsch  thanks for the PR i am goin to close the issue so :+1:
