### ISSUE TITLE
when combined with semantic-ui, the styles went wrong

### ISSUE THREAD

**Issue by ghostboyzone** [720kb/angular-tooltips#3]

**Comment by 45kb** [comment]
@ghostboyzone Hi, i am trying to check your code locally (cloned your fork locally)... but i get errors in console, don't you get them?

http://imgur.com/mookuqV

Also please remember to run npm install  and grunt to check all possible errors ;)

Waiting for your working version.

thanks a lot

**Comment by ghostboyzone** [comment]
I got the reason from [https://docs.angularjs.org/error/jqLite/nosel](https://docs.angularjs.org/error/jqLite/nosel), that's to say I have to rewrite my code to only use tag name selectors and manually traverse the DOM using the APIs provided by jqLite rather than using jquery api.  You can test the effects by including the jquery lib inside, and I'll rewrite it the day after tomorrow

**Comment by 45kb** [comment]
@ghostboyzone  no problems, could be great if you create a new semantic-ui.html inside the root directory of the project so we can put that in the main repo to show that semantic-ui is supported. (as you can see i included an index.html and a twitter-bootstrap.html in the project that is the pourpose, to show supported frameworks togheter :+1:  )

**Comment by 45kb** [comment]
the new version including your fix is here https://github.com/720kb/angular-tooltips/releases/tag/0.1.4 you should be able to get it via bower install to! 

thank you @ghostboyzone  :)

**Comment by ghostboyzone** [comment]
@45kb  Let me know if there's any problems

**Comment by 45kb** [comment]
@ghostboyzone  sure , thank you :)
