### ISSUE TITLE
resize tooltip for small-screens

### ISSUE THREAD

**Issue by armyofda12mnkeys** [720kb/angular-tooltips#33]
I just wanted to comment first thanking you for this great plugin.
Not even the Angular UI-Bootstrap has the 'auto'-placement feature that tooltrip-try="1" does (Bootstrap does but its not implemented in UI-Bootstrap). 
Most of my site's popups went over the top, or sides of the website with UI-Bootstrap even on desktop browsers.

I was going to ask if its possible to set it up so when on a small-screen something more mobile friendly happens, as this is the only time I still see unusual behavior. 
Like when starting off my desktop browser with a small width, the tooltips still goes off screen.

Also using mobile is just a weird experience with all tooltips I have used.
I thought about this and thought the nicest thing would be to auto-add a special icon like a font-awesome '?' or 'i' that users know to click for more info next to the abbreviation/definition they are placing the tooltip on. 
and if you click on that on icon hyperlink, it opens a fairly large tooltip-info window so they can read it on mobile. It may have an 'X' at the top (and/or close button button at bottom) so that you can close it (and/or auto-disappears after 10 seconds).
Not sure if this would be within scope for angular-tooltips but just thought I'd mention it would be a nice functionality that you can turn on with maybe a tooltip-definition="true" or maybe tooltip-mobile-friendly="true" to indication if want to turn on the optional feature to auto-add this '?' hyperlink for mobile.

Thanks again,
Ari

P.S. I'm using your plugin like so:
```
Do you have <em class="glossary" tooltips=""  tooltip-side="top" tooltip-try="1" tooltip-content="Irritable Bower Syndrome is a disease which can affect alot of people... ">IBS</em>?
```

**Comment by 45kb** [comment]
Hi @armyofda12mnkeys  at the moment there is not a feature for this, if you want you can try making something by forking the repo and PR the changes, then we will keep an eye on this scenario.

So, for the moment i suggest  you one solution, you can easily detect window width and set up your own scope variable when it's a small devices and then show the related tooltip, something like this:

    <a tooltips ng-if="isDesktop" tooltip-content="Click on the button <button>more...</button>">Tooltip</a>
    <a tooltips ng-if="isMobile" tooltip-content="Don't click the button read here">Tooltip</a>

**Comment by armyofda12mnkeys** [comment]
Cool, the isMobile/isDesktop is exactly what i did last night (haven't implemented what to do on mobile yet though since its a bit tricky being in a checkbox label like that, might have to prevent default from the checkbox being selected if you click the '?' icon):

**Desktop:**
![Desktop](https://farm9.staticflickr.com/8745/17114634407_851957398b_o.png)

**versus Mobile:**
![Mobile](https://farm8.staticflickr.com/7712/17134284328_8549e53f52_o.png)
