### ISSUE TITLE
Possible to show tooltip at particular position conditional?

### ISSUE THREAD

**Issue by stanleyxu2005** [720kb/angular-tooltips#34]
I've a chart widget. I want to show HTML tooltip near the cursor when mouse is over the chart. Is it possible with angular-tooltips?

**Comment by wouldgo** [comment]
Hi @stanleyxu2005,

if you want to show a tooltip bounded on the elements that represent the bars, to achieve your target you can use the directive on that elements. 

@45kb correct me if I'm wrong.

**Comment by 45kb** [comment]
@stanleyxu2005  hi, yes as @wouldgo said, for example:

    <chart tooltips tooltip-title="Mouse over"></chart>

**Comment by stanleyxu2005** [comment]
The content is expected to be dynamic. I simplified my use case with following code example:
```
<chart tooltips tooltip-title="{{angular_variable}}"></chart>

// In Angular Controller
$scope.angular_variable = "Hello world";
onCertainEvent: function(element) {
$scope.angular_variable = "Dynamic content: " + element;
}
```

The tooltip will not be updated.

**Comment by 45kb** [comment]
@stanleyxu2005  so you want to show dynamic content, which is a feature actually in progress https://github.com/720kb/angular-tooltips/pull/24

Not possible at the moment, but they are working on it

**Comment by stanleyxu2005** [comment]
Thanks and great project!

**Comment by 45kb** [comment]
@stanleyxu2005 you're welcome, thank you for asking :+1:
