### ISSUE TITLE
Tooltip doesn't update if title is dynamically changed.

### ISSUE THREAD

**Issue by jhubbardsf** [720kb/angular-tooltips#35]
Tooltip's don't update if their title is dynamically changed. If you have any angular markup in them then it'll just leave those spots blank, even after being updated.

**Comment by kagd** [comment]
The same goes for the tooltip content as well.

**Comment by rockblings** [comment]
Same experience

**Comment by 45kb** [comment]
Hi, yes sorry for that, people is working on it https://github.com/720kb/angular-tooltips/pull/24 , https://github.com/720kb/angular-tooltips/pull/37, looks like soon it will be fixed!

**Comment by 45kb** [comment]
Hi, you can now test the latest changes https://github.com/720kb/angular-tooltips/pull/37 thanks to @KynoYang 

I am going to close this issue but if any problem please re-open it and let us know, thank you a lot for reporting!
