### ISSUE TITLE
ngSanitize (if available)

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-tooltips#39]
If ngSanitize module is available, title and content should be ng-bind-html and sanitized

**Comment by cs-NET** [comment]
@45kb I just ran into a XSS vulnerability with the tooltip-html attribute.

      $scope.getHtml = function(){
            return $sce.trustAsHtml($scope.html);
        };

The current code above prevents the sanitizing of the HTML allowing for XSS to be rendered in the DOM. By default I do not think this behavior should be allowed, maybe add an additional attribute asTrusted and change the code to something like:

    $scope.getHtml = function(){
        if(tooltipHtmlAsTrusted) {    
            return $sce.trustAsHtml($scope.html);
        } else {
            return $scope.html;
        }
    };

TL;DR: The ng-bind-html will sanitize the html by default; adding $sce.trustAsHtml() actually prevents sanitizing the html (which should not be default behavior).

Thoughts?

**Comment by cs-NET** [comment]
@45kb I am now using the tooltip-view and tooltip-view-model attributes to  implement my custom html without having to worry about exposing unsafe html via the tooltip-html attribute. This seems to be a clean solution. I would maybe recommend still adding a warning about tooltip-html being trusted html and not sanitized.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case.

This is the only reason why i am going to close this issue.

Thank you and feel free to ask if any doubt or question about the new version.

**Comment by sunsheeppoplar** [comment]
I'm running into issues that seem to fall into this category. Is there any way to make sure that the tooltip **doesn't** run something as HTML?

```<h3 class="manage-docs-folder-container__each__name" tooltips tooltip-template="{{folder.name}}" tooltip-side="bottom">{{ folder.name }}</h3>```

We noticed this is vulnerable to code like this ```<img src=1 onerror=alert(1)>```
