### ISSUE TITLE
Delayd tooltip

### ISSUE THREAD

**Issue by GipHub123** [720kb/angular-tooltips#42]
Thanks for a great directive :) 

Tooltip animation seems to start right away. 
It would be nice to have a delayed tooltip which starts animation after x milliseconds. 
If user moves cursor away, animation is cancelled.

**Comment by 45kb** [comment]
Hi @GipHub123  this is a cool feature, would/could you like to try something for this? 
Let know, help is much appreciated!

**Comment by 45kb** [comment]
Available with the new version here:  https://github.com/720kb/angular-tooltips/releases/tag/0.1.11
