### ISSUE TITLE
Enabling and disabling tooltip

### ISSUE THREAD

**Issue by GipHub123** [720kb/angular-tooltips#43]
Thanks for a great directive :) 

It would be nice to be able to disable and enable tooltips. 
Sometimes tooltips might be a bit annoying if they keep popping up each time when mouse is moved over etc.
This feature would make it real easy to show tooptip only once etc. 
"Hey did you notice this nice feature?"

**Comment by 45kb** [comment]
Another good feature, if you try something for this let know, we will try as soon as it's possible :+1:

**Comment by dominique-mueller** [comment]
Found out that a tooltip only shows when a tooltip-title is being set.
So making the tooltip title dynamic (e.g. by choosing between "some text ...." or an empty string "" with an expression) you can hide and show it whenever you want.

Maybe that might help ;)

**Comment by 45kb** [comment]
Yes @dominique-mueller thank you.

Definitely if you empty ```title=""``` ```tooltip-title=""``` and ```tooltip-content=""``` it will not show.
