### ISSUE TITLE
Tooltips in ng-repeat

### ISSUE THREAD

**Issue by miguelleite** [720kb/angular-tooltips#48]
Hey there. First of all, nice work with these simple-to-use tooltips.
Any way we can set a conditional to add or not the tooltip in a ng-repeat, based on a scope variable?

Thanks in advance.

**Comment by wouldgo** [comment]
Hi @miguelleite,

have you thought to put an ng-if or an ng-show on the element where the tooltip attribute is placed?
I think that you can achieve your goal with this.

Is it fittable for your needs?
Hoping that this not generates any issues :grin: 

Dario

**Comment by miguelleite** [comment]
Hey @wouldgo, thanks for your answer.

ng-show is not an option, because i want the element to be shown anyway, i just don't want the tooltip to show in some elements.
ng-if seems like an option, though i'm trying to solve this using ng-attr-tooltips. Will give feedback on this asap.

**Comment by miguelleite** [comment]
@wouldgo coudn't do it with the ng-attr, so used the ng-if. Thanks for the tip.

**Comment by wouldgo** [comment]
@miguelleite No problem at all "_sharing is caring_".
Closing, anyway if you encounter problems do not hesitate to come back!
