### ISSUE TITLE
binding html to content

### ISSUE THREAD

**Issue by sagivf** [720kb/angular-tooltips#49]
Would be nice to be able to add html to content.
I think it was possible, but broke when content was made dynamic

**Comment by sagivf** [comment]
Add pull request https://github.com/720kb/angular-tooltips/pull/50

**Comment by 45kb** [comment]
Hi @sagivf  as you read from the PR i link you to the correct issue that was opened exactly for this pourpose https://github.com/720kb/angular-tooltips/issues/39
