### ISSUE TITLE
tooltip-side not always being honoured.

### ISSUE THREAD

**Issue by jeffhuys** [720kb/angular-tooltips#55]
Great library! I ran into a little issue which I can't seem to solve. I have a directive which dynamically adds a tooltip to a set of images like this:

    for(var slug in categoriesTable){
        var categoryUrl = baseURL + categoriesTable[slug];

        var URLToAppend = '<img src="'; 
              URLToAppend += _.contains(scope.categories, slug)? categoryUrl + ".svg" : categoryUrl + "_unavailable.svg";
              URLToAppend += '" tooltips tooltip-side="bottom" tooltip-title="';
              URLToAppend += slug;
              URLToAppend += '">';

        var elementToAppend = angular.element(URLToAppend);
        element.append(elementToAppend);

        $compile(elementToAppend)(scope);
    }

The first time I call this directive, it shows up like it should (on the bottom), however the second time it's called it shows up on the right hand side.
I inspect the first and the second elements in Chrome's inspector but both the HTML outputs are the same.

Any insight is greatly appreciated.

**Comment by 45kb** [comment]
Hi @jeffhuys  have you tried with tooltip-try="false" ?

Can you please show a plunkr or jsfiddle so we can investigate the problem?

thank you!

**Comment by jeffhuys** [comment]
Thanks for the quick reply! That worked, thank you so much. I assume `tooltip-try="false"` disables a system that checks if the tooltip is outside of the screen or something similar?

**Comment by 45kb** [comment]
@jeffhuys You're welcome, yes the problem is that ```tooltip-try="true"``` (which is by default if not specified)  tries to find a best position (top,left,right or bottom) in the screen when space is not enough.

It surely need some check, glad if you solved for the moment!

Thank you.
