### ISSUE TITLE
interacting with tooltip

### ISSUE THREAD

**Issue by drone-ah** [720kb/angular-tooltips#59]
We are looking to add some html into the tooltip which the user can interact with (5 star rating). However, we are currently having to set it to hide on click since the tooltip disappears when the mouse is moved into the tooltip.

How easy would it be to change it so that the tooltip stays open if the mouse is moved on to the tooltip? It should be hidden only if the mouse is not on the original element OR the tooltip itself.

**Comment by 45kb** [comment]
@drone-ah  Hi, have you already tried tooltip-hide-trigger=""  ?

that way you can pass every event you want the tooltip to hide on

for example:

```
tooltip-hide-trigger="click mouseout"
```
Isn't it enough for your problem?

**Comment by drone-ah** [comment]
Hi, That doesn't seem to work since as soon as the mouse moves out of the element, the tooltip disappears.

What it needs to do is put in a delay before the tooltip disappears and if the mouse is over the tooltip, the hide should be cancelled. This is at least one way of doing it.

I actually went ahead and hacked that in to a fork - https://github.com/drone-ah/angular-tooltips/commit/7bb847ee9b3a8ebe67c83ea99f9b6f70031e28d3

I can re-do that as a pull request if it helps.

**Comment by 45kb** [comment]
Now it's clear what you trying to achieve so focusout will not work.

Thanks for the Fork i see the code maybe we can try something without having to use $timeout, let's see.

:+1:

**Comment by wouldgo** [comment]
@Ryppy :100:

**Comment by 45kb** [comment]
@drone-ah  Try now :), use this https://github.com/720kb/angular-tooltips#tooltip-hide-trigger-target and you should be ok!

Going to close the issue, you can re-open it at anytime if needed.

Thanks @Ryppy :+1:
