### ISSUE TITLE
Dynamic html content (ng-bind) within tooltip-html?

### ISSUE THREAD

**Issue by envision** [720kb/angular-tooltips#60]
Hi,

How to embed dynamic html content for the tooltip? I need to calculate values for the content, for example:

    <span ng-bind='event.duration / 3600 | number:2'></span>

PS. It would be nice to be able to have html content loaded optionally from view files. Angular UI library has had problems with that so there are not many options around.

**Comment by 45kb** [comment]
@envision Hi this is not possible at the moment, we hope to make something for this asap, if you would try something and PR it we'll be much appreciated, thank you!

**Comment by envision** [comment]
The solution for this problem – go to sleep! ...in the morning I woke up before alarm and the solution for this problem was in my mind.

View:

    <div id="mebeingaparent" ng-controller="ChartCtrl">
        <span class="glyphicons glyphicons-circle-info quickInfoTooltip" tooltips tooltip-html="{{htmlTooltip}}"></span>
    </div>

In controller:

    $scope.htmlTooltip = "<div>Total hours <span>{{ 7200 / 3600 }}</span></div>";

**Comment by 45kb** [comment]
@envision awesome, so now it works :dancers: 

I am going to close the issue, feel free to re-open this in case it's needed.

**Comment by envision** [comment]
Actually now I'm having another problem, as I need to wait for an API request to get the data... The tooltip html content has already been applied, and even if I change the variable's content the tooltip is showing the default value. Is there a way to refresh the tooltips?

**Comment by 45kb** [comment]
@envision  could you join here https://gitter.im/720kb so we can talk about it live

**Comment by 45kb** [comment]
@envision  here better https://gitter.im/720kb/angular-tooltips
