### ISSUE TITLE
Tooltip does not show on mobile device

### ISSUE THREAD

**Issue by pliablepixels** [720kb/angular-tooltips#63]
Hello, I am developing an app using ionic and am using your tooltips to display tooltips for input labels like so:

```
 <label class="item item-input item-floating-label "  tooltips tooltip-content='Hello'>
                <span class="input-label">username</span>
                <input autocapitalize="none" autocomplete="off"
                       autocorrect="off" type="text"
                       placeholder="username"
                       ng-model="loginData.username">
            </label>
```

It works fine on desktop but when I move it to a mobile device (tested in iOS) it does not show up.
Do you know why? Do I need to use a special trigger for mobile devices?

thanks

**Comment by pliablepixels** [comment]
Okay, I figured this out. If I do 
```
tooltip-show-trigger="ng-click click"
```
It works on both desktop and mobile (as ionic traps ng-click)

Now how can I hide the tool-tip after a few seconds? I don't want to hide on ng-click again - if I show many tool tips it gets messy on a mobile. Thanks

**Comment by 45kb** [comment]
@pliablepixels  try using a css animation for that and delay it, it's the simplest way.

There are  ```tooltip-delay``` and ```tooltip-hide-trigger``` but actually i don't think they will work togheter.

**Comment by pliablepixels** [comment]
Thank you. I'll start exploring that path - I think it would be an easy fix. The bigger problem I am facing now is that when the view scrolls (for example when seen in a phone, the window scrolls) -- the tooltips don't scroll along with them, so they point to absolute positions. I'll try and figure out a solution for that too

**Comment by 45kb** [comment]
@pliablepixels  yes it is a known missing feature, when scrolling or when inside a scrollable area,  we need to make it to follow the element while scrolling.

Thank you let know if you try something for this :+1:

**Comment by zeeshan-ahmad-butt** [comment]
@pliablepixels , i want to hide tool tip after some second, did you find any solution if it ?

**Comment by 45kb** [comment]
@zeeshan-ahmad-butt  The new tooltip version uses CSS animations to show and hide tooltips, if you want to delay animations just go for a new CSS rule 👍
