### ISSUE TITLE
Tooltip when scrolling X/Y

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-tooltips#64]
Tooltip needs to follow his element when scrolling in the page or in the scrollable area

**Comment by hpeinar** [comment]
Made a PR to fix tooltip positioning issues on scrollable areas. 
https://github.com/720kb/angular-tooltips/pull/65

**Comment by 45kb** [comment]
thank you @hpeinar  , https://github.com/720kb/angular-tooltips/releases/tag/0.1.15

**Comment by 45kb** [comment]
@dislick i referred the issue here, if you want you can paste some code and we can check what is happening.

Thank you for reporting

**Comment by 45kb** [comment]
Closed you may re-open it if you need. thank you
