### ISSUE TITLE
Tooltips are incorrectly positioned after scrolling in a container

### ISSUE THREAD

**Issue by dislick** [720kb/angular-tooltips#67]
Hey!

So I found this bug in your directive where when a user scrolls in a DIV with `overflow: scroll`, it does not re-calculate the position of the element. `tooltip-lazy` and `tooltip-scroll` do not help either.

Here are some screenshots:

**Before: (expected)**

![tooltip ok](https://cloud.githubusercontent.com/assets/3121902/8798084/08d74376-2fa0-11e5-88aa-348fea0721d8.PNG)

**After: (unexpected)**

![tooltip not ok](https://cloud.githubusercontent.com/assets/3121902/8798080/0564db18-2fa0-11e5-96f2-f8930d1f92f0.PNG)

**Comment by 45kb** [comment]
@dislick  Hi, could you please show some code, better a plunkr or a jsfiddle.

thank you.

**Comment by 45kb** [comment]
closing and referring to https://github.com/720kb/angular-tooltips/issues/67
