### ISSUE TITLE
Fade out transition

### ISSUE THREAD

**Issue by dominique-mueller** [720kb/angular-tooltips#68]
Right now the tooltip is nicely fading in when hovering over an element - but when leaving the area the tooltip disappears without any transition.

Wouln't it be nice to also have an fading out transition, maybe shorter that the fading in one ?

**Comment by 45kb** [comment]
HI @dominique-mueller  yes could be great to have same feature on hiding, feel free to try something and PR if you want :+1:

**Comment by dominique-mueller** [comment]
Added with commit df4f8f499b1462a85ea5beb792a05498e8f84c97

**Comment by 45kb** [comment]
Thank you @dominique-mueller  released in a new version https://github.com/720kb/angular-tooltips/releases/tag/0.1.16
