### ISSUE TITLE
visibility:initial is not supported on IE

### ISSUE THREAD

**Issue by KynoYang** [720kb/angular-tooltips#7]
Hi, guys. I find tooltip doesn't work well on IE and the reason is IE doesn't support "visibility: initial". So, why not use "visible"?

**Comment by 45kb** [comment]
@KynoYang  Hi, thank you for reporting, which IE version?
 what about a fallback? 

have you tried just for example:

{
visibility:visible;
visibility:initial;
}

**Comment by KynoYang** [comment]
http://www.w3schools.com/cssref/css_initial.asp  initial isn't supported by IE, every version. :disappointed: 

I've tried with "visible".   Do you mean put them together, like your comment?

**Comment by 45kb** [comment]
@KynoYang  Yes try please :)

**Comment by KynoYang** [comment]
The style in your comment works. IE doesn't support "initial", so "visible" works. On other browsers, "initial" overwrites "visible".  Cool!

**Comment by 45kb** [comment]
@KynoYang  Awesome, PR if you want this was a huge bug, thank you!

**Comment by 45kb** [comment]
Here the new version with Ie support thanks to you https://github.com/720kb/angular-tooltips/releases/tag/0.1.6
