### ISSUE TITLE
Tooltip-view watcher

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-tooltips#71]
Should be great to have a watcher when tooltip-view is specified, since if the specified view gets updated the tooltip should be recalculated.

Actually if you dynamically change the view content tooltip is not updated

**Comment by 45kb** [comment]
https://github.com/720kb/angular-tooltips/issues/78

**Comment by danzaner** [comment]
+1 Would be really useful to be able to dynamically change the view while the tooltip is being displayed!

**Comment by Shuunen** [comment]
+1 :) cannot use the library without this feature

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this issue.

Thank you and feel free to ask if any doubt or question about the new version.
