### ISSUE TITLE
Tooltips over other icons with tooltips can't be clicked

### ISSUE THREAD

**Issue by joaocmfcm** [720kb/angular-tooltips#72]
Hello, I was on v0.1.9 I guess and today I updated my dependencies. Since then, with the latest v0.1.18 my tooltips overlap the other icon's "events" that have some kind of clickable/hover behaviors.
You can see on the following printscreen that this work fine, but notice that this tooltip is over an icon on the row above:
http://i.imgur.com/REcIqTo.png
As result, when I put my mouse over the icon on that row above the icon, it cannot trigger its events (show the tooltip, trigger the :hover css rule, trigger the ng-click):
http://i.imgur.com/vJ90v2S.png

How can I fix this?

Thanks

**Comment by 45kb** [comment]
@joaocmfcm  Hi could you please show your html, a jsfiddle or working plunkr could be great anyway.

**Comment by joaocmfcm** [comment]
Downgraded to version v0.1.16 and it's working like it should.
My HTML is really simple

`<td> 
					<i class="fa fa-cog clickable-icon" tooltips tooltip-title="{{ 'GENERAL.BUTTONS.EDIT' | translate}}" tooltip-size="small" ng-click="appManagerCtrl.editApplication(app.id)"></i>
					<i class="fa fa-trash-o clickable-icon" tooltips tooltip-title="{{ 'GENERAL.BUTTONS.DELETE' | translate}}" tooltip-size="small" ng-click="appManagerCtrl.deleteApplication(app.id)"></i> 
				</td>`

**Comment by 45kb** [comment]
Quite strange, is it working with ```0.1.17```?

**Comment by joaocmfcm** [comment]
Sorry I mean v0.1.17 is the version I got it working. On v0.1.16 I had other issue with tooltips inside scrollable lists. I guess is just a v0.1.18 problem this "overlapping" of events. I will stay on v0.1.17 for now

**Comment by 45kb** [comment]
I don't understand what's wrong with the 0.1.18 since 0.1.17 works the exact same way of, very strange, could be great to investigate better your problem...  Can't you link a plunkr or jsfiddle? :+1:
