### ISSUE TITLE
String interpolation from scope variables?

### ISSUE THREAD

**Issue by danielabar** [720kb/angular-tooltips#74]
Is it possible to have string interpolation in the template? I'm trying to generate tooltips for a list of items in a repeater. 

Example controller:

```javascript
// items actually gets populated from a service, and that from $http earlier in the process
$scope.items = [
  {name: 'foo', description: 'some details about foo',
 ...
]
```

And the view iterates over these items and displays them in a condensed form (just first few characters of the name), because space is limited.

Then trying to have the tooltip show the full name, so the template for tooltip:

```
{{item.name}}
<br>
{{item.description}}
```

But it doesn't interpolate. I tried passing in a controller to the tooltip, but couldn't figure out how to share the particular item instance that user is hovered over to the tooltip controller.

**Comment by 45kb** [comment]
@danielabar  Hi, are you using both ```tooltip-view=""``` and ```tooltip-ctrl=""``` ?

It's hard to guess what's happening could you please provide some working fiddle or plunkr ?

Thank you

**Comment by 45kb** [comment]
https://github.com/720kb/angular-tooltips/issues/78

**Comment by danielabar** [comment]
Sorry for not getting back sooner, had a tight deadline and ended up building a custom directive for the tooltips, so I don't have the code anymore.

But yes I was trying to use `tooltip-view` and `tooltip-view-ctrl`, and the view was trying to reference scope variables. But they were not being rendered.

**Comment by 45kb** [comment]
@danielabar Hi, please post a fiddle or plunkr with your code, in my tests everything is working fine...

thank you
