### ISSUE TITLE
tooltip-hide-target "tooltip" never hides tooltip

### ISSUE THREAD

**Issue by rDr4g0n** [720kb/angular-tooltips#76]
Setting `tooltip-hide-target` attribute to "tooltip" causes a visible tooltip to never hide.

https://github.com/720kb/angular-tooltips/commit/6c43c83e3c8a8bbf4d0f3fa9673f29a84206948b prevents tooltips from receiving mousevents, so the tooltip never emits the `hideTriggers` events.

**Comment by 45kb** [comment]
@Ryppy  do you know anything about this?

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this issue.

Thank you and feel free to ask if any doubt or question about the new version.
