### ISSUE TITLE
Dynamically changing tooltip content on form errors

### ISSUE THREAD

**Issue by rohanchandane** [720kb/angular-tooltips#78]
I am trying to integrate angular-tooltips with input form. I want to change tooltip text on ```registrationForm.email.$error``` object change.

HTML:
`<input tooltips tooltip-html="{{ emailToolTip }}" tooltip-show-trigger="focus" tooltip-hide-trigger="blur" tooltip-side="right"/>`
`<div>{{emailToolTip}}</div>`

Controller:
```javascript
$scope.emailToolTip = 'Initial tooltip';
$scope.$watch('registrationForm.email.$error', function (newVal) {
  $scope.emailToolTip = 'Updated tooltip';
  }
}, true);
```
above code changes `<div>` value but it doesn't change `<input>`'s 'tooltip-html' attribute value. Am I missing anything or is it a bug?

**Comment by 45kb** [comment]
@rohanchandane Hi, atm there are no observers for the attributes, soon there will be.

You can do what you want using somenthing like this:

```html
<a tooltips tooltip-view="/path/to/view.html" tooltip-view-ctrl="myFormCtrl">
Tooltip
</a>
```

**Comment by rDr4g0n** [comment]
I am not sure if this is the right approach, but I have some changes to bind tooltip-html to the template rather than concatenating it as a regular string. This means that any changes to the tooltip-html will flow all the way down and trigger a redraw in the tooltip. The downside is it requires ngSanitize to use trustAsHtml() on that property, which I guess could be a security issue?  

Anyway if this sounds useful, i can make a PR for it.

**Comment by 45kb** [comment]
@rDr4g0n   hi, yes there is an opened issue for that https://github.com/720kb/angular-tooltips/issues/39

If ngsanitize is available could be great to html-bind the content of tooltip-html if you are so gentle to try something let know .

Imho you should use tooltip-view and tooltip-view-ctrl if your tooltip html is articulated

**Comment by rDr4g0n** [comment]
@45kb I think you're right, using a proper view and controller is probably the better choice, but it is certainly tempting to just shove a few bound values into some HTML.

**Comment by rDr4g0n** [comment]
I put up a PR that might help. If it doesn't quite fit in with how you guys want to do this, please feel free to close it. 

https://github.com/720kb/angular-tooltips/pull/79

**Comment by rohanchandane** [comment]
Good stuff! Thanks Guys.

**Comment by 45kb** [comment]
Thanks @rDr4g0n  will test it later and let you know, so, does you fixed the security problem with html only or there is something more/else?

**Comment by 45kb** [comment]
Shipped the new version https://github.com/720kb/angular-tooltips/tree/0.1.22

Thank you a lot !
