### ISSUE TITLE
Tooltip only shows up right

### ISSUE THREAD

**Issue by rollrockofficial** [720kb/angular-tooltips#80]
I cannot seem to make the tooltip go on the bottom. I have added "720kb.tooltips" as a dependency, added angular-tooltip.min.js in my javascripts, and added the angular-tooltip.min.css to my css links as well. 

The tool tip works perfectly fine. It just won't seem to change position from the original right.

<strong> I am using:</strong>
Angular 1.3.16,
Bootstrap CSS & JS: 3.3.5,
and Django: 1.8

    <a 
        class="about-social a-color" 
        tooltips 
        tooltip-title="Austin on Linkedin" 
        tooltip-size="small" 
        tootip-side="bottom"  
        href="https://www.linkedin.com/in/" 
        target="_blank">
            <span class="icon-linkedin"></span>
      </a>

![screen shot 2015-08-20 at 3 29 06 pm](https://cloud.githubusercontent.com/assets/7155853/9397322/3d04c070-4750-11e5-8983-88b4fb9a5158.png)

**Comment by 45kb** [comment]
@rollrockofficial  Hi, add ```tooltip-try="false"``` and let me know :+1:

**Comment by rollrockofficial** [comment]
@45kb Thank you! Yes that corrected it.

**Comment by 45kb** [comment]
@rollrockofficial  awesome, glad if it works :+1:

**Comment by panzerdp** [comment]
+1
probably makes sense to change `tooltip-try="false"` if the tooltip position is setup manually.
Thanks.
