### ISSUE TITLE
Wrong syntax in the CSS file

### ISSUE THREAD

**Issue by sahan91** [720kb/angular-tooltips#81]
I fixed a syntax error in the CSS file where the visibility attribute was wrongly spelt. Also, fixed spacing issues in the whole angular-tooltips.css file. I can create a pull request to if you can let me commit to the codebase.

**Comment by wouldgo** [comment]
Hi @sahan91,

Thank you for investigating and found an angular-tooltipo problem: you should fork this repo, fix what you discovered as issue then make a PR against this repo. Then we can review and accept the PR releasing the fixes as soon as possible.

If there are any doubts don't esitate to ask here, you're welcome!

**Comment by sahan91** [comment]
Hey @wouldgo,

Thanks a lot for the prompt reply. I forked and created a PR. Hope it's all good :)

**Comment by wouldgo** [comment]
Thank you man, we missed the typo! :dart:
