### ISSUE TITLE
Does not work with CommonJS

### ISSUE THREAD

**Issue by mchambaud** [720kb/angular-tooltips#86]
Will not work with CommonJS/Browserify

**Comment by wouldgo** [comment]
#87 related. Am I right?

**Comment by mchambaud** [comment]
yes!

**Comment by wouldgo** [comment]
We encounter some problems during testing, not related to your PR

**Comment by wouldgo** [comment]
@mchambaud atm we released `angular-tooltips@0.1.23` with your modification. It works as the previous versions of the tooltip.
Anyway the issues encountered are still there but they are some limit use case.

Thanks for your patience.

Dario

**Comment by mchambaud** [comment]
@wouldgo Thanks mate!
