### ISSUE TITLE
Resizing the screen with multiple tooltip cause performance issues

### ISSUE THREAD

**Issue by MathRivest** [720kb/angular-tooltips#88]
Great plugin btw, super easy to use!  

I have this project with a lot of tooltips (a ng-repeat with tons of items) but when I get to 50+ items (so 100+ tooltips) and I resize the screen, it reinitialize all the tooltips and cause massive performance issue.

Thanks for looking in that issue

`angular.element($window).bind('resize', onResize);` seems to be the problem

**Comment by 45kb** [comment]
@MathRivest  Hi thanks for reporting , this is a known problem actually.

We will try soon to refactor the code, don't worry :+1:

**Comment by mchambaud** [comment]
+1

**Comment by jonyw4** [comment]
+ 1

**Comment by mchambaud** [comment]
Scroll interval also kills the performance.

**Comment by wouldgo** [comment]
Could be a feasible way integrate these events inside a `requestAnimationFrame`?

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.
