### ISSUE TITLE
Can't click on tooltips because of point-events: none

### ISSUE THREAD

**Issue by tanin47** [720kb/angular-tooltips#89]
When I click on the tooltip, the click goes through the tooltip to the element behind it. Is it intentional to be this way?

reference: https://github.com/720kb/angular-tooltips/blob/master/src/css/angular-tooltips.css#L14

**Comment by 45kb** [comment]
Hi @tanin47
That line in the css was a fix for IE8 bad behavior.
Let's ping @Ryppy he could help on this

However, my suggestion is to use your own customized css.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.

**Comment by tanin47** [comment]
ok, thanks for the info. Will try and let you know.
