### ISSUE TITLE
Add support for smooth animations

### ISSUE THREAD

**Issue by 45kb** [720kb/angular-tooltips#9]
Could be great to specify a new attribute, something like:

< a tooltips tooltip-speed="fast | medium  | slow | int" > tooltip me < /a >

**Comment by KynoYang** [comment]
That will be helpful.

**Comment by 45kb** [comment]
@KynoYang  would you do that to? :) feel free, seriously :) i have no time at the moment

**Comment by KynoYang** [comment]
@45kb I can do it in this weekend. I have to do my project first.  Is that OK?

**Comment by wouldgo** [comment]
:clap: 
Really thanks @KynoYang for your commitment.

**Comment by 45kb** [comment]
@KynoYang  Sure! Let me know if any trouble we can discuss about this feature here, i don't have a clear plan for this, maybe using  css classes is ok but could be great to pass also milliseconds to the new attribute (int)....

**Comment by wouldgo** [comment]
I prefer a set of css transition that apply "movement" to the tooltip container.

**Comment by 45kb** [comment]
I agree :)

**Comment by 45kb** [comment]
@KynoYang  something went wrong? Thanks for your help

**Comment by 45kb** [comment]
closed, thanks to @KynoYang
