### ISSUE TITLE
Tooltip lazy loading

### ISSUE THREAD

**Issue by lukaszbulzacki** [720kb/angular-tooltips#92]
Hi,

Is there a way to lazy load tooltip title/content at event eg. onmouseover?
I have many tooltips in form that need to be processed before showing.

**Comment by 45kb** [comment]
@lukaszbulzacki  Hi, yes you can use (tooltip-view)[https://github.com/720kb/angular-tooltips#tooltip-view] and (tooltip-view-ctrl)[https://github.com/720kb/angular-tooltips#tooltip-view-ctrl]

**Comment by lukaszbulzacki** [comment]
Oh thanks.

**Comment by 45kb** [comment]
You're welcome at anytime :+1:
