### ISSUE TITLE
Using tooltip-html throws error

### ISSUE THREAD

**Issue by stschaefer** [720kb/angular-tooltips#93]
Hi,

first of all: Thanks for your directive. Good work.

I'm trying to use the "tooltip-html" attribute as explained in your documentation but I get an error in the browser's console: 

```
Uncaught Error: [$parse:syntax] Syntax Error: Token '<' not a primary expression at column 1 of the expression [<i>Woa!</i>] starting at [<i>Woa!</i>].
```

When I'm using ```tooltip-html="TEST äöü"``` it says:
```
Uncaught Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 5-5 [ä] in expression [TEST äöü].
```
Do you have an idea what I'm doing wrong?

Thanks for your help. Greetings,
Stefan

**Comment by 45kb** [comment]
@stschaefer Hi, sorry for the delay, actually, i am unable to replicate the bug, i tried ```tooltip-html="TEST äöü"``` but it works to me.

Can you please provide a jsfiddle or plnkr with your code?

Thank you.

**Comment by 45kb** [comment]
We performed a refactor that completely changes the behavior (new module version).

We also revised all the attributes/options (see Readme.md), could be great if you can try the new version and give us feedback in case. 

This is the only reason why i am going to close this PR.

Thank you and feel free to ask if any doubt or question about the new version.
