### ISSUE TITLE
Trigger tooltip based on form validation

### ISSUE THREAD

**Issue by celsomtrindade** [720kb/angular-tooltips#96]
Is it possible to trigger the tooltip event based on a input being invalid?

I'm trying like this:
    
    <form name="test" novalidate>
    <input type="text" placeholder="Field name" ng-model="test1" required
		tooltips 
		tooltip-title="tip" 
		tooltip-title="Hey"
		tooltip-show-trigger="test.test1.$invalid" 
		tooltip-content="<i>Woa!</i>" />
    </form>

But nothing is happening.

**Comment by wouldgo** [comment]
Hi @celsomtrindade,

[here](https://github.com/720kb/angular-tooltips#tooltip-triggers) we report the usage for the tooltip-show-trigger. At the moment only mouse events are managed, so your snippet doesn't work.

**Comment by 45kb** [comment]
Hi, the only way (at the moment) is to use a css class like this:


```css
.show {
visiblity:visible !important;
}
.hide{
visibility:hidden !important;
}
```
```html
<form name="test" novalidate>
<input type="text" placeholder="Field name" ng-model="test1" required
   ng-class="{'show': test.test1.$invalid, 'hide': test.test1.$invalid}" 
   tooltips 
    tooltip-title="tip" 
    tooltip-title="Hey"
    tooltip-content="<i>Woa!</i>" />
</form>
```
It's a dirty work around that should work.

**Comment by kotmatpockuh** [comment]
@45kb 
why you added class to input?

**Comment by 45kb** [comment]
@kotmatpockuh Hi, is just an example but you could use ng-show and ng-hide i guess.

Classes are hiding/showing the input conditionally here.

**Comment by kotmatpockuh** [comment]
but it show/hide input, not tooltip(

**Comment by 45kb** [comment]
Yes my fault sorry :D

**Comment by kotmatpockuh** [comment]
Any ideas how to solve it?
Or maybe give an advice where and what to change it the code...

**Comment by 45kb** [comment]
There are two available attribute options `tooltip-show-trigger` and `tooltip-hide-trigger` you could trigger the events you pass through them on the element when you want to show or hide the tooltip.

**Comment by kotmatpockuh** [comment]
But it supports only mouse events.

**Comment by kotmatpockuh** [comment]
also it must support something lilke: tooltip-show-trigger="test.test1.$invalid"

**Comment by gkohen** [comment]
Does anyone know why this issue has been closed?
